;; DOUBLE LINKED LIST PART

;; creates the templates required for the list
(defrecord dListNode [next data prev])
(defrecord dList [head tail])

;; checks if the list is empty
(defn dListEmpty? [lst]
  (nil? @(:tail lst)))

;; appends a new node with a given value to the list
(defn dListAppend [lst val]
  (dosync
    (ref-set (:tail lst)
      (dListNode. (ref nil) val (ref @(:tail lst))))
    (if (not (nil? @(:head lst)))
        (ref-set (:next @(:prev @(:tail lst)))
          @(:tail lst))
        (ref-set (:head lst)
          @(:tail lst)))))

;; gives the first element of the list
(defn dListFirst [lst]
  (:data @(:head lst)))

;; gives the second element of the list
(defn dListLast [lst]
  (:data @(:tail lst)))

;; removes the element from the beginning of the list
(defn dListRemFirst [node lst]
  (ref-set (:prev @(:next node))
    nil)
  (ref-set (:head lst)
    @(:next node))
  (ref-set (:next node)
    nil))

;; removes the element fron the end of the list
(defn dListRemLast [node lst]
  (ref-set (:next @(:prev node))
    nil)
  (ref-set (:tail lst)
    @(:prev node))
  (ref-set (:prev node)
    nil))

;; removes the given element
;; which is in the middle of the list
(defn dListRemMiddle [node]
  (ref-set (:next @(:prev node))
    @(:next node))
  (ref-set (:prev @(:next node))
    @(:prev node))
  (ref-set (:prev node)
    nil)
  (ref-set (:next node)
    nil))

;; resets the list
(defn dListRemAll [lst]
  (ref-set (:head lst)
    nil)
  (ref-set (:tail lst)
    nil))

;; function to remove a given element from the list
(defn dListDeleteElement [node lst]
  (dosync
    (if (and (nil? @(:prev node))
             (nil? @(:next node)))
      (dListRemAll lst)
      (if (nil? @(:prev node))
        (dListRemFirst node lst)
        (if (nil? @(:next node))
          (dListRemLast node lst)
          (dListRemMiddle node))))))

;; function to convert a double linked list
;; into a predifined Clojure list
(defn dListIntoClojureList [dList]
  (with-local-vars [resultList ()]
    (loop [node (deref (:tail dList))]
      (when (not (nil? node))
        (var-set resultList (conj @resultList (:data node)))
        (recur (deref (:prev node)))))
    @resultList))

;; GRAPH PART
;; vertex states: unseen(0) open(1) current(2) visited(3)

;; creates the templates required for the graph
(defrecord graph [vertices vertexMap])
(defrecord vertex [label status neighbors distance])
(defrecord neighbor [index weight])

;; creates an empty graph
(defn makeGraph []
  (graph. (ref []) (ref {})))

;; gives a vertex by its label
(defn callVertexLabel [label g]
  (get @(:vertices g) (get @(:vertexMap g) label)))

;; gives a vertex by its index
(defn callVertexIndex [index g]
  (get @(:vertices g) index))

;; adds a new vertex to the graph
(defn graphAddVertex [g label]
  (dosync
    (ref-set (:vertexMap g)
      (assoc @(:vertexMap g) label (count @(:vertices g))))
    (ref-set (:vertices g)
      (conj @(:vertices g) (vertex. label (ref 0) (ref ()) (ref 0))))))

;; adds edges to the graph
;; by adding neighbours to the vertices
(defn graphAddEdge [g l1 l2 w]
  (dosync
    (ref-set (:neighbors (callVertexLabel l1 g))
      (conj @(:neighbors (callVertexLabel l1 g))
        (neighbor. (get @(:vertexMap g) l2) w)))
    (ref-set (:neighbors (callVertexLabel l2 g))
      (conj @(:neighbors (callVertexLabel l2 g))
        (neighbor. (get @(:vertexMap g) l1) w)))))

;; resets the status and total distance of all vertices
(defn verticesReset [g]
  (doseq [vertex @(:vertices g)]
    (dosync
      (ref-set (:status vertex) 0)
      (ref-set (:distance vertex) 0))))

;; DIJKSTRA'S ALGORITHM PART

;; selects the vertex with the smallest total distance
;; from the open queue (double linked list)
(defn selectFromQueue [opQueue g]
  (with-local-vars [selectedVertex @(:head opQueue)]
    (loop [node @(:head opQueue)]
      (when (not (nil? node))
        (if (< @(:distance (callVertexLabel (:data node) g))
               @(:distance (callVertexLabel (:data @selectedVertex) g)))
          (var-set selectedVertex node))
        (recur @(:next node))))
    (dListDeleteElement @selectedVertex opQueue)
    (:data @selectedVertex)))

;; selects the given vertex's neighbour
;; with the smallest total distance
(defn selectMinDistance [currentVertex g]
  (with-local-vars [selectedVertex
                    (first @(:neighbors (callVertexLabel currentVertex g)))]
    (doseq [neighbor @(:neighbors (callVertexLabel currentVertex g))]
      (if (< @(:distance (callVertexIndex (:index neighbor) g))
             @(:distance (callVertexIndex (:index @selectedVertex) g)))
        (var-set selectedVertex neighbor)))
    @selectedVertex))

;; processes a neighbour with an unseen (0) status using edge's weights
(defn processUnseenNeighbor [currentVertex neighbor opQueue g]
  (dListAppend opQueue (:label (callVertexIndex (:index neighbor) g)))
  (ref-set (:status (callVertexIndex (:index neighbor) g))
    1)
  (if (= 0 @(:distance (callVertexIndex (:index neighbor) g)))
    (ref-set (:distance (callVertexIndex (:index neighbor) g))
      (+ @(:distance (callVertexLabel currentVertex g))
         (:weight neighbor)))))

;; processes a neighbour with an open (1) status using edge's weights
(defn processOpenNeighbor [currentVertex neighbor g]
  (if (< (+ @(:distance (callVertexLabel currentVertex g))
            (:weight neighbor))
         @(:distance (callVertexIndex (:index neighbor) g)))
    (ref-set (:distance (callVertexIndex (:index neighbor) g))
      (+ @(:distance (callVertexLabel currentVertex g))
         (:weight neighbor)))))

;; processes a neighbour with an unseen (0) status
;; without using edge's weights
(defn processNeighborUsingHops [currentVertex neighbor opQueue g]
  (dListAppend opQueue (:label (callVertexIndex (:index neighbor) g)))
  (ref-set (:status (callVertexIndex (:index neighbor) g))
    1)
  (ref-set (:distance (callVertexIndex (:index neighbor) g))
    (inc @(:distance (callVertexLabel currentVertex g)))))

;; the main function to process a neighbour
;; it calls one of the three functions based on the scenario
(defn processNeighbors [currentVertex opQueue g hops]
  (if hops
    (doseq [neighbor @(:neighbors (callVertexLabel currentVertex g))]
      (when (= 0 @(:status (callVertexIndex (:index neighbor) g)))
        (processNeighborUsingHops currentVertex neighbor opQueue g)))
    (doseq [neighbor @(:neighbors (callVertexLabel currentVertex g))]
      (if (= 0 @(:status (callVertexIndex (:index neighbor) g)))
        (processUnseenNeighbor currentVertex neighbor opQueue g)
        (if (= 1 @(:status (callVertexIndex (:index neighbor) g)))
          (processOpenNeighbor currentVertex neighbor g))))))

;; the main function to process the vertex with the current (2) status
(defn processCurrentVertex [opQueue g hops]
  (let [currentVertex (selectFromQueue opQueue g)]
    (dosync
      (ref-set (:status (callVertexLabel currentVertex g))
        2)
      (processNeighbors currentVertex opQueue g hops)
      (ref-set (:status (callVertexLabel currentVertex g))
        3))))

;; starter/main function for the marking phase
(defn dijkstraMarkingGraph [opQueue g hops]
  (when (not (dListEmpty? opQueue))
    (processCurrentVertex opQueue g hops)
    (dijkstraMarkingGraph opQueue g hops)))

;; starter/main function for the backtracking phase
;; it outputs a Clojure list with the shortest path
(defn dijkstraCreatePath [path g]
  (loop [currentVertex (dListFirst path)]
    (when (not (= 0 @(:distance (callVertexLabel currentVertex g))))
      (let [neighbor (selectMinDistance currentVertex g)]
        (dListAppend path (:label (callVertexIndex (:index neighbor) g))))
      (recur (dListLast path))))
  (println "Total distance:"
    @(:distance (callVertexLabel (dListFirst path) g)))
  (dListIntoClojureList path))

;; starter finction for the Dijkstra's algorithm
;; prepares the graph/queue/output list
(defn dijkstra [g start finish & [hops]]
  (verticesReset g)
  (let [opQueue (dList. (ref nil) (ref nil))
        path (dList. (ref nil) (ref nil))]
    (dListAppend opQueue finish)
    (dListAppend path start)
    (if (= start finish)
      (dListIntoClojureList path)
      (do
        (if hops
          (dijkstraMarkingGraph opQueue g true)
          (dijkstraMarkingGraph opQueue g false))
        (if (= 0 @(:distance (callVertexLabel start g)))
          (do
            (println "There is no path to the destination")
            (list))
          (dijkstraCreatePath path g))))))

;; GRAPH INITIALISATION PART

(def g (makeGraph))
(graphAddVertex g "Hîrsova")
(graphAddVertex g "Baku")
(graphAddVertex g "Samara")
(graphAddVertex g "Ormenio")
(graphAddVertex g "Napoca")
(graphAddVertex g "Orel")
(graphAddVertex g "Makhachkala")
(graphAddVertex g "Ystad")
(graphAddVertex g "Gedser")
(graphAddVertex g "Bad Hersfeld")
(graphAddVertex g "Copenhagen")
(graphAddVertex g "Opole")
(graphAddVertex g "Rhion")
(graphAddVertex g "Bishkek")
(graphAddVertex g "Tarvisio")
(graphAddVertex g "Sassari")
(graphAddVertex g "Göttingen")
(graphAddVertex g "Örebro")
(graphAddVertex g "Brno")
(graphAddVertex g "Oulu")
(graphAddVertex g "Kissamos")
(graphAddVertex g "Berlin")
(graphAddVertex g "Goleniów")
(graphAddVertex g "Heinola")
(graphAddVertex g "Ioannina")
(graphAddVertex g "Jelenia Góra")
(graphAddVertex g "Beaune")
(graphAddVertex g "Jizzakh")
(graphAddVertex g "Villach")
(graphAddVertex g "Omsk")
(graphAddVertex g "Nusaybin")
(graphAddVertex g "Slonim")
(graphAddVertex g "Udine")
(graphAddVertex g "Yerevan")
(graphAddVertex g "Khmel'nyts'kyi")
(graphAddVertex g "Ohrid")
(graphAddVertex g "Dubrovnik")
(graphAddVertex g "Genova")
(graphAddVertex g "Kirovohrad")
(graphAddVertex g "Lødingen")
(graphAddVertex g "Yalta")
(graphAddVertex g "Kozani")
(graphAddVertex g "Folkestone")
(graphAddVertex g "Simferopol")
(graphAddVertex g "Ravenna")
(graphAddVertex g "Petrovac")
(graphAddVertex g "Rostov na Donu")
(graphAddVertex g "Buchara")
(graphAddVertex g "Lódz")
(graphAddVertex g "Wroclaw")
(graphAddVertex g "Imst")
(graphAddVertex g "St. Margrethen")
(graphAddVertex g "Nykøbing Falster")
(graphAddVertex g "Dublin")
(graphAddVertex g "Podgorica")
(graphAddVertex g "Fulda")
(graphAddVertex g "Habur")
(graphAddVertex g "Kraków")
(graphAddVertex g "Korinthos")
(graphAddVertex g "Frøslev")
(graphAddVertex g "Paris")
(graphAddVertex g "Ferrand")
(graphAddVertex g "Vilnius")
(graphAddVertex g "Siret")
(graphAddVertex g "Trieste")
(graphAddVertex g "Rimini")
(graphAddVertex g "Balkhash")
(graphAddVertex g "Uzhhorod")
(graphAddVertex g "Catania")
(graphAddVertex g "Rovaniemi")
(graphAddVertex g "Trento")
(graphAddVertex g "Astana")
(graphAddVertex g "Warsaw")
(graphAddVertex g "Vrsac")
(graphAddVertex g "Volgograd")
(graphAddVertex g "Amsterdam")
(graphAddVertex g "Postojna")
(graphAddVertex g "Plzen")
(graphAddVertex g "Bekdash")
(graphAddVertex g "Brugge")
(graphAddVertex g "Berne")
(graphAddVertex g "Ridder")
(graphAddVertex g "Turnu Severin")
(graphAddVertex g "Bellinzona")
(graphAddVertex g "Farø")
(graphAddVertex g "Rijeka")
(graphAddVertex g "Palermo")
(graphAddVertex g "Prešov")
(graphAddVertex g "Eisenach")
(graphAddVertex g "Rennes")
(graphAddVertex g "Esbjerg")
(graphAddVertex g "Mukacheve")
(graphAddVertex g "Cluj")
(graphAddVertex g "San Sebastián")
(graphAddVertex g "Taranto")
(graphAddVertex g "Jihlava")
(graphAddVertex g "Nizhniy Panj")
(graphAddVertex g "Karagandy")
(graphAddVertex g "Lamia")
(graphAddVertex g "Chambéry")
(graphAddVertex g "Astara")
(graphAddVertex g "Niki")
(graphAddVertex g "Murcia")
(graphAddVertex g "Brjansk")
(graphAddVertex g "Batumi")
(graphAddVertex g "Zielona Góra")
(graphAddVertex g "Limerick")
(graphAddVertex g "Ipswich")
(graphAddVertex g "Rosenheim")
(graphAddVertex g "Lübbenau")
(graphAddVertex g "Kurgan")
(graphAddVertex g "Å")
(graphAddVertex g "Pavlodar")
(graphAddVertex g "Cardiff")
(graphAddVertex g "Suceava")
(graphAddVertex g "Lorient")
(graphAddVertex g "Egion")
(graphAddVertex g "Kaunas")
(graphAddVertex g "Vejle")
(graphAddVertex g "Vercelli")
(graphAddVertex g "Metaponto")
(graphAddVertex g "Târgu Mures")
(graphAddVertex g "Tripoli")
(graphAddVertex g "Sicignano")
(graphAddVertex g "Razgrad")
(graphAddVertex g "Metz")
(graphAddVertex g "Bonifacio")
(graphAddVertex g "Kicevo")
(graphAddVertex g "Alexandroupolis")
(graphAddVertex g "Povorino")
(graphAddVertex g "Novorossijsk")
(graphAddVertex g "Kirkenes")
(graphAddVertex g "Sary Tash")
(graphAddVertex g "Iraklion")
(graphAddVertex g "Swiecie")
(graphAddVertex g "Dubno")
(graphAddVertex g "Uralsk")
(graphAddVertex g "Ryazan")
(graphAddVertex g "Skopje")
(graphAddVertex g "Chaniá")
(graphAddVertex g "Mont Blanc")
(graphAddVertex g "Landeck")
(graphAddVertex g "Bastia")
(graphAddVertex g "Helsingborg")
(graphAddVertex g "Ganca")
(graphAddVertex g "Zhambyl")
(graphAddVertex g "Geneva")
(graphAddVertex g "Ivalo")
(graphAddVertex g "Tours")
(graphAddVertex g "Moscow")
(graphAddVertex g "Gerede")
(graphAddVertex g "Stryj")
(graphAddVertex g "Lisbon")
(graphAddVertex g "Valencia")
(graphAddVertex g "Lyon")
(graphAddVertex g "Århus")
(graphAddVertex g "Castellón de la Plana")
(graphAddVertex g "Utrecht")
(graphAddVertex g "Telfs")
(graphAddVertex g "Dnipropetrovsk")
(graphAddVertex g "Bregenz")
(graphAddVertex g "Veliko Tarnovo")
(graphAddVertex g "Bursa")
(graphAddVertex g "Hamburg")
(graphAddVertex g "Alushta")
(graphAddVertex g "Dole")
(graphAddVertex g "Inari")
(graphAddVertex g "Alat")
(graphAddVertex g "Murmansk")
(graphAddVertex g "Izmir")
(graphAddVertex g "Roman")
(graphAddVertex g "Samsun")
(graphAddVertex g "Voronezh")
(graphAddVertex g "Saint Petersburg")
(graphAddVertex g "Modena")
(graphAddVertex g "Fiano")
(graphAddVertex g "Ucharal")
(graphAddVertex g "Vardø")
(graphAddVertex g "Karshi")
(graphAddVertex g "Tábor")
(graphAddVertex g "Lida")
(graphAddVertex g "Linz")
(graphAddVertex g "Püspökladány")
(graphAddVertex g "Kharkiv")
(graphAddVertex g "Malmö")
(graphAddVertex g "Patrai")
(graphAddVertex g "Málaga")
(graphAddVertex g "Preston")
(graphAddVertex g "Vienna")
(graphAddVertex g "Kiruna")
(graphAddVertex g "Orléans")
(graphAddVertex g "Budapest")
(graphAddVertex g "Žilina")
(graphAddVertex g "Messina")
(graphAddVertex g "Chernivtsi")
(graphAddVertex g "Ufa")
(graphAddVertex g "Rajka")
(graphAddVertex g "Uman'")
(graphAddVertex g "Montargis")
(graphAddVertex g "Olpe")
(graphAddVertex g "Swinoujscie")
(graphAddVertex g "Cosenza")
(graphAddVertex g "Drobeta")
(graphAddVertex g "Chelyabinsk")
(graphAddVertex g "Innsbruck")
(graphAddVertex g "Birmingham")
(graphAddVertex g "Gothenburg")
(graphAddVertex g "Rivne")
(graphAddVertex g "San Sebastian")
(graphAddVertex g "Luleå")
(graphAddVertex g "Mosonmagyaróvár")
(graphAddVertex g "Ljubljana")
(graphAddVertex g "Kalamata")
(graphAddVertex g "Szczecin")
(graphAddVertex g "Girona")
(graphAddVertex g "Almería")
(graphAddVertex g "Donetsk")
(graphAddVertex g "Villa San Giovanni")
(graphAddVertex g "Greenock")
(graphAddVertex g "Porto Vecchio")
(graphAddVertex g "Emmerich")
(graphAddVertex g "Split")
(graphAddVertex g "Odesa")
(graphAddVertex g "Vordingborg")
(graphAddVertex g "Legnica")
(graphAddVertex g "Alexandria")
(graphAddVertex g "Pescara")
(graphAddVertex g "Heidelberg")
(graphAddVertex g "London")
(graphAddVertex g "Würzburg")
(graphAddVertex g "Khashuri")
(graphAddVertex g "Bozen")
(graphAddVertex g "Bucharest")
(graphAddVertex g "Helsingør")
(graphAddVertex g "Nuremberg")
(graphAddVertex g "Southampton")
(graphAddVertex g "San Gottardo")
(graphAddVertex g "Lauterach")
(graphAddVertex g "Orange")
(graphAddVertex g "Osnabrück")
(graphAddVertex g "Kassel")
(graphAddVertex g "Navoi")
(graphAddVertex g "Sattledt")
(graphAddVertex g "Alicante")
(graphAddVertex g "Bad Oeynhausen")
(graphAddVertex g "Sevilla")
(graphAddVertex g "Jirgatal")
(graphAddVertex g "Priština")
(graphAddVertex g "Rotterdam")
(graphAddVertex g "Vyšné Nemecké")
(graphAddVertex g "Urziceni")
(graphAddVertex g "Bristol")
(graphAddVertex g "Melbu")
(graphAddVertex g "Winterthur")
(graphAddVertex g "Strasbourg")
(graphAddVertex g "Craiova")
(graphAddVertex g "Jyväskylä")
(graphAddVertex g "Fano")
(graphAddVertex g "Mannheim")
(graphAddVertex g "Rozvadov")
(graphAddVertex g "Porto Torres")
(graphAddVertex g "Felixstowe")
(graphAddVertex g "Teplice")
(graphAddVertex g "Kyzylorda")
(graphAddVertex g "Tortona")
(graphAddVertex g "Karlsruhe")
(graphAddVertex g "Shoumen")
(graphAddVertex g "Ordu")
(graphAddVertex g "Ternopil'")
(graphAddVertex g "Brallos")
(graphAddVertex g "Ankara")
(graphAddVertex g "Zürich")
(graphAddVertex g "Utsjoki")
(graphAddVertex g "Ayaguz")
(graphAddVertex g "Swansea")
(graphAddVertex g "Semey")
(graphAddVertex g "Alessandria")
(graphAddVertex g "Newport")
(graphAddVertex g "Ishim")
(graphAddVertex g "Rome")
(graphAddVertex g "Turda")
(graphAddVertex g "Hanover")
(graphAddVertex g "Naryn")
(graphAddVertex g "Georgiyevka")
(graphAddVertex g "Yaroslavl")
(graphAddVertex g "Amasya")
(graphAddVertex g "Erfurt")
(graphAddVertex g "Klaipeda")
(graphAddVertex g "Bologna")
(graphAddVertex g "Tambov")
(graphAddVertex g "Antirrion")
(graphAddVertex g "Salerno")
(graphAddVertex g "Florence")
(graphAddVertex g "Ayni")
(graphAddVertex g "Varangerbotn")
(graphAddVertex g "Gyzylarbat")
(graphAddVertex g "St. Gallen")
(graphAddVertex g "L'viv")
(graphAddVertex g "Nice")
(graphAddVertex g "Chardzhu")
(graphAddVertex g "Reims")
(graphAddVertex g "Homel")
(graphAddVertex g "Gürbulak")
(graphAddVertex g "Oradea")
(graphAddVertex g "Frankfurt am Main")
(graphAddVertex g "Arkalyk")
(graphAddVertex g "Angers")
(graphAddVertex g "Sofia")
(graphAddVertex g "Fortezza")
(graphAddVertex g "Kuba")
(graphAddVertex g "Manchester")
(graphAddVertex g "Shymkent")
(graphAddVertex g "Slobozia")
(graphAddVertex g "Tallinn")
(graphAddVertex g "Edinburgh")
(graphAddVertex g "Ruse")
(graphAddVertex g "Fetisovo")
(graphAddVertex g "Oostende")
(graphAddVertex g "Zalaegerszeg")
(graphAddVertex g "Luxembourg")
(graphAddVertex g "Mulhouse")
(graphAddVertex g "Saarbrücken")
(graphAddVertex g "Heilbronn")
(graphAddVertex g "Bratislava")
(graphAddVertex g "Sodankylä")
(graphAddVertex g "Katowice")
(graphAddVertex g "Ivrea")
(graphAddVertex g "Ghent")
(graphAddVertex g "Mineralnye Vody")
(graphAddVertex g "Amersfoort")
(graphAddVertex g "Arnhem")
(graphAddVertex g "The Hague")
(graphAddVertex g "Bijelo Polje")
(graphAddVertex g "Harrachov")
(graphAddVertex g "Esil")
(graphAddVertex g "Gelibolu")
(graphAddVertex g "Sitía")
(graphAddVertex g "Cagliari")
(graphAddVertex g "Alyat")
(graphAddVertex g "Braunschweig")
(graphAddVertex g "Železný Brod")
(graphAddVertex g "Køge")
(graphAddVertex g "Lucerne")
(graphAddVertex g "Pyrgos")
(graphAddVertex g "Zhetybai")
(graphAddVertex g "Letenye")
(graphAddVertex g "Dushanbe")
(graphAddVertex g "Nalchik")
(graphAddVertex g "Szombathely")
(graphAddVertex g "Torugart")
(graphAddVertex g "Shetpe")
(graphAddVertex g "Liverpool")
(graphAddVertex g "Szolnok")
(graphAddVertex g "Ploiesti")
(graphAddVertex g "Aachen")
(graphAddVertex g "Fishguard")
(graphAddVertex g "Feldkirch")
(graphAddVertex g "Liège")
(graphAddVertex g "Gela")
(graphAddVertex g "Prague")
(graphAddVertex g "Csorna")
(graphAddVertex g "Istanbul")
(graphAddVertex g "Le Mans")
(graphAddVertex g "Madrid")
(graphAddVertex g "Rosslare")
(graphAddVertex g "Görlitz")
(graphAddVertex g "Verona")
(graphAddVertex g "Como")
(graphAddVertex g "Evenes")
(graphAddVertex g "Kobrin")
(graphAddVertex g "Karlovac")
(graphAddVertex g "Fredrikshavn")
(graphAddVertex g "Luhans'k")
(graphAddVertex g "Armavir")
(graphAddVertex g "Domokos")
(graphAddVertex g "Kolding")
(graphAddVertex g "Newcastle")
(graphAddVertex g "Dresden")
(graphAddVertex g "Aalborg")
(graphAddVertex g "Canosa")
(graphAddVertex g "Olten")
(graphAddVertex g "Kemi")
(graphAddVertex g "Szeged")
(graphAddVertex g "Minsk")
(graphAddVertex g "Cologne")
(graphAddVertex g "Perth")
(graphAddVertex g "Wolin")
(graphAddVertex g "Athens")
(graphAddVertex g "Parma")
(graphAddVertex g "Belgrade")
(graphAddVertex g "A Coruña")
(graphAddVertex g "Guzai")
(graphAddVertex g "Buonfornello")
(graphAddVertex g "Glukhov")
(graphAddVertex g "Sortland")
(graphAddVertex g "Samarkand")
(graphAddVertex g "Nagykanizsa")
(graphAddVertex g "Töre")
(graphAddVertex g "Piotrków Trybunalski")
(graphAddVertex g "Islamic Republic of Iran")
(graphAddVertex g "Megri")
(graphAddVertex g "Svolvær")
(graphAddVertex g "Turin")
(graphAddVertex g "Altdorf")
(graphAddVertex g "Kastanies")
(graphAddVertex g "Stockholm")
(graphAddVertex g "Goris")
(graphAddVertex g "Aosta")
(graphAddVertex g "Lugano")
(graphAddVertex g "Narva")
(graphAddVertex g "Bilbao")
(graphAddVertex g "Kalamáta")
(graphAddVertex g "Gyor")
(graphAddVertex g "Besançon")
(graphAddVertex g "Bitola")
(graphAddVertex g "Border of the Islamic Republic of Iran")
(graphAddVertex g "Chemnitz")
(graphAddVertex g "Vladikavkaz")
(graphAddVertex g "Colchester")
(graphAddVertex g "Clermont")
(graphAddVertex g "Atyrau")
(graphAddVertex g "Beineu")
(graphAddVertex g "Mladá Boleslav")
(graphAddVertex g "Merzifon")
(graphAddVertex g "Gliwice")
(graphAddVertex g "Nukus")
(graphAddVertex g "Mazara del Vallo")
(graphAddVertex g "Barcelona")
(graphAddVertex g "Bordeaux")
(graphAddVertex g "Siracusa")
(graphAddVertex g "Vadsø")
(graphAddVertex g "Giurgiu")
(graphAddVertex g "Salzburg")
(graphAddVertex g "Reggio di Calabria")
(graphAddVertex g "Giresun")
(graphAddVertex g "Halmstad")
(graphAddVertex g "Milan")
(graphAddVertex g "Magdeburg")
(graphAddVertex g "Narvik")
(graphAddVertex g "Lahti")
(graphAddVertex g "Erzurum")
(graphAddVertex g "Lausanne")
(graphAddVertex g "Sherobod")
(graphAddVertex g "Dover")
(graphAddVertex g "Dasoguz")
(graphAddVertex g "Evlak")
(graphAddVertex g "Wexford")
(graphAddVertex g "Larissa")
(graphAddVertex g "Munich")
(graphAddVertex g "Zhezkazgan")
(graphAddVertex g "Kostanai")
(graphAddVertex g "Adana")
(graphAddVertex g "Brussels")
(graphAddVertex g "Stara Zagora")
(graphAddVertex g "Tedjen")
(graphAddVertex g "Narbonne")
(graphAddVertex g "Georgiyevska")
(graphAddVertex g "Sary")
(graphAddVertex g "Vinnytsia")
(graphAddVertex g "Almaty")
(graphAddVertex g "Susa")
(graphAddVertex g "Tbilisi")
(graphAddVertex g "Glasgow")
(graphAddVertex g "Eindhoven")
(graphAddVertex g "Flensburg")
(graphAddVertex g "Cork")
(graphAddVertex g "Varna")
(graphAddVertex g "Constanta")
(graphAddVertex g "Wörgl")
(graphAddVertex g "Kungrad")
(graphAddVertex g "Preveza")
(graphAddVertex g "Gouda")
(graphAddVertex g "Tarragona")
(graphAddVertex g "Maikapshagai")
(graphAddVertex g "Poti")
(graphAddVertex g "Zagreb")
(graphAddVertex g "Kumanovo")
(graphAddVertex g "Trencin")
(graphAddVertex g "Algeciras")
(graphAddVertex g "Samtredia")
(graphAddVertex g "Bad Reichenhall")
(graphAddVertex g "Vevi")
(graphAddVertex g "Gera")
(graphAddVertex g "Arlon")
(graphAddVertex g "Pskov")
(graphAddVertex g "Helsinki")
(graphAddVertex g "Waterford")
(graphAddVertex g "Offenburg")
(graphAddVertex g "Petropavl")
(graphAddVertex g "Irkeshtam")
(graphAddVertex g "Agios Nikolaos")
(graphAddVertex g "Brescia")
(graphAddVertex g "Brindisi")
(graphAddVertex g "Rostock")
(graphAddVertex g "Didymoteicho")
(graphAddVertex g "Slavonski Brod")
(graphAddVertex g "Igoumenitsa")
(graphAddVertex g "Haskovo")
(graphAddVertex g "Auxerre")
(graphAddVertex g "Petrozavodsk")
(graphAddVertex g "Chiasso")
(graphAddVertex g "Calais")
(graphAddVertex g "Ozek")
(graphAddVertex g "Smolensk")
(graphAddVertex g "Le Havre")
(graphAddVertex g "Cesena")
(graphAddVertex g "Palmanova")
(graphAddVertex g "Mestre")
(graphAddVertex g "Tashkent")
(graphAddVertex g "Nickelsdorf")
(graphAddVertex g "Belfort")
(graphAddVertex g "Hoek van Holland")
(graphAddVertex g "Bari")
(graphAddVertex g "Piacenza")
(graphAddVertex g "Taldykorgan")
(graphAddVertex g "Sankt Pölten")
(graphAddVertex g "Penza")
(graphAddVertex g "Swiebodzin")
(graphAddVertex g "Nantes")
(graphAddVertex g "Timisoara")
(graphAddVertex g "Svilengrad")
(graphAddVertex g "Ashgabat")
(graphAddVertex g "Iraq")
(graphAddVertex g "Maastricht")
(graphAddVertex g "Termis")
(graphAddVertex g "Kingston upon Hull")
(graphAddVertex g "Brest")
(graphAddVertex g "Vannes")
(graphAddVertex g "Trabzon")
(graphAddVertex g "Ancona")
(graphAddVertex g "Oldenzaal")
(graphAddVertex g "Saint Avold")
(graphAddVertex g "Burubaytal")
(graphAddVertex g "Astrakhan")
(graphAddVertex g "Niš")
(graphAddVertex g "Oberhausen")
(graphAddVertex g "Shannon")
(graphAddVertex g "Naples")
(graphAddVertex g "Przemysl")
(graphAddVertex g "Brenner")
(graphAddVertex g "Öskemen")
(graphAddVertex g "Basel")
(graphAddVertex g "Bastogne")
(graphAddVertex g "Thessaloniki")
(graphAddVertex g "Kaluga")
(graphAddVertex g "Derzhavinsk")
(graphAddVertex g "Mary")
(graphAddVertex g "Kyiv")
(graphAddVertex g "Zhytomyr")
(graphAddVertex g "Turnov")
(graphAddVertex g "Poznan")
(graphAddVertex g "Gorzów Wielkopolski")
(graphAddVertex g "Inverness")
(graphAddVertex g "Taskesken")
(graphAddVertex g "Byala")
(graphAddVertex g "Perugia")
(graphAddVertex g "Turkmenbashi")
(graphAddVertex g "Brasov")
(graphAddVertex g "Lapseki")
(graphAddVertex g "Toulouse")
(graphAddVertex g "Itea")
(graphAddVertex g "Wetzlar")
(graphAddVertex g "Gdansk")
(graphAddVertex g "Brest nad Bugem")
(graphAddEdge g "Lapseki" "Bursa" 203)
(graphAddEdge g "Bursa" "Ankara" 323)
(graphAddEdge g "Ankara" "Adana" 390)
(graphAddEdge g "Adana" "Nusaybin" 523)
(graphAddEdge g "Nusaybin" "Habur" 2962)
(graphAddEdge g "Habur" "Iraq" 886)
(graphAddEdge g "Igoumenitsa" "Ioannina" 53)
(graphAddEdge g "Ioannina" "Thessaloniki" 207)
(graphAddEdge g "Thessaloniki" "Alexandroupolis" 249)
(graphAddEdge g "Alexandroupolis" "Gelibolu" 82)
(graphAddEdge g "Reggio di Calabria" "Metaponto" 272)
(graphAddEdge g "Metaponto" "Taranto" 38)
(graphAddEdge g "Taranto" "Brindisi" 62)
(graphAddEdge g "Mazara del Vallo" "Palermo" 84)
(graphAddEdge g "Palermo" "Buonfornello" 45)
(graphAddEdge g "Buonfornello" "Messina" 152)
(graphAddEdge g "Lisbon" "Madrid" 503)
(graphAddEdge g "Madrid" "Barcelona" 506)
(graphAddEdge g "Dubrovnik" "Priština" 251)
(graphAddEdge g "Priština" "Sofia" 176)
(graphAddEdge g "Sofia" "Istanbul" 504)
(graphAddEdge g "Istanbul" "Izmir" 328)
(graphAddEdge g "Izmir" "Gerede" 508)
(graphAddEdge g "Gerede" "Amasya" 306)
(graphAddEdge g "Amasya" "Erzurum" 469)
(graphAddEdge g "Erzurum" "Gürbulak" 211)
(graphAddEdge g "Gürbulak" "Islamic Republic of Iran" 482)
(graphAddEdge g "Lisbon" "San Sebastián" 789)
(graphAddEdge g "San Sebastián" "Toulouse" 278)
(graphAddEdge g "Toulouse" "Nice" 469)
(graphAddEdge g "Nice" "Genova" 154)
(graphAddEdge g "Genova" "Rome" 401)
(graphAddEdge g "Rome" "Pescara" 155)
(graphAddEdge g "Samsun" "Ordu" 134)
(graphAddEdge g "Ordu" "Giresun" 43)
(graphAddEdge g "Giresun" "Trabzon" 112)
(graphAddEdge g "Trabzon" "Batumi" 175)
(graphAddEdge g "Batumi" "Poti" 3348)
(graphAddEdge g "A Coruña" "Bilbao" 442)
(graphAddEdge g "Bilbao" "San Sebastián" 77)
(graphAddEdge g "San Sebastián" "Bordeaux" 202)
(graphAddEdge g "Bordeaux" "Clermont" 807)
(graphAddEdge g "Clermont" "Ferrand" 456)
(graphAddEdge g "Ferrand" "Lyon" 104)
(graphAddEdge g "Lyon" "Chambéry" 87)
(graphAddEdge g "Chambéry" "Susa" 100)
(graphAddEdge g "Susa" "Turin" 49)
(graphAddEdge g "Turin" "Alessandria" 75)
(graphAddEdge g "Alessandria" "Tortona" 19)
(graphAddEdge g "Tortona" "Brescia" 128)
(graphAddEdge g "Brescia" "Verona" 61)
(graphAddEdge g "Verona" "Mestre" 97)
(graphAddEdge g "Mestre" "Palmanova" 94)
(graphAddEdge g "Palmanova" "Trieste" 45)
(graphAddEdge g "Trieste" "Postojna" 37)
(graphAddEdge g "Postojna" "Ljubljana" 38)
(graphAddEdge g "Ljubljana" "Zagreb" 116)
(graphAddEdge g "Zagreb" "Slavonski Brod" 174)
(graphAddEdge g "Slavonski Brod" "Belgrade" 196)
(graphAddEdge g "Belgrade" "Vrsac" 74)
(graphAddEdge g "Vrsac" "Timisoara" 70)
(graphAddEdge g "Timisoara" "Drobeta" 168)
(graphAddEdge g "Drobeta" "Turnu Severin" 0)
(graphAddEdge g "Turnu Severin" "Craiova" 97)
(graphAddEdge g "Craiova" "Alexandria" 128)
(graphAddEdge g "Alexandria" "Bucharest" 80)
(graphAddEdge g "Bucharest" "Giurgiu" 61)
(graphAddEdge g "Giurgiu" "Ruse" 5)
(graphAddEdge g "Ruse" "Razgrad" 58)
(graphAddEdge g "Razgrad" "Shoumen" 43)
(graphAddEdge g "Shoumen" "Varna" 80)
(graphAddEdge g "Turkmenbashi" "Gyzylarbat" 303)
(graphAddEdge g "Gyzylarbat" "Ashgabat" 217)
(graphAddEdge g "Ashgabat" "Tedjen" 196)
(graphAddEdge g "Tedjen" "Mary" 120)
(graphAddEdge g "Mary" "Chardzhu" 224)
(graphAddEdge g "Chardzhu" "Alat" 40)
(graphAddEdge g "Alat" "Buchara" 66)
(graphAddEdge g "Buchara" "Karshi" 154)
(graphAddEdge g "Karshi" "Guzai" 151)
(graphAddEdge g "Guzai" "Sherobod" 238)
(graphAddEdge g "Sherobod" "Termis" 52)
(graphAddEdge g "Termis" "Dushanbe" 195)
(graphAddEdge g "Dushanbe" "Jirgatal" 175)
(graphAddEdge g "Jirgatal" "Sary Tash" 230)
(graphAddEdge g "Sary Tash" "Irkeshtam" 56)
(graphAddEdge g "Poti" "Samtredia" 3308)
(graphAddEdge g "Samtredia" "Khashuri" 105)
(graphAddEdge g "Khashuri" "Tbilisi" 105)
(graphAddEdge g "Tbilisi" "Ganca" 172)
(graphAddEdge g "Ganca" "Evlak" 1951)
(graphAddEdge g "Evlak" "Baku" 1666)
(graphAddEdge g "Brest" "Lorient" 109)
(graphAddEdge g "Lorient" "Vannes" 46)
(graphAddEdge g "Vannes" "Nantes" 103)
(graphAddEdge g "Nantes" "Angers" 80)
(graphAddEdge g "Angers" "Tours" 93)
(graphAddEdge g "Tours" "Orléans" 107)
(graphAddEdge g "Orléans" "Montargis" 62)
(graphAddEdge g "Montargis" "Auxerre" 66)
(graphAddEdge g "Auxerre" "Beaune" 128)
(graphAddEdge g "Beaune" "Dole" 50)
(graphAddEdge g "Dole" "Besançon" 43)
(graphAddEdge g "Besançon" "Belfort" 77)
(graphAddEdge g "Belfort" "Mulhouse" 37)
(graphAddEdge g "Mulhouse" "Basel" 28)
(graphAddEdge g "Basel" "Zürich" 74)
(graphAddEdge g "Zürich" "Winterthur" 19)
(graphAddEdge g "Winterthur" "St. Gallen" 49)
(graphAddEdge g "St. Gallen" "St. Margrethen" 20)
(graphAddEdge g "St. Margrethen" "Bregenz" 9)
(graphAddEdge g "Bregenz" "Feldkirch" 31)
(graphAddEdge g "Feldkirch" "Landeck" 74)
(graphAddEdge g "Landeck" "Telfs" 41)
(graphAddEdge g "Telfs" "Innsbruck" 24)
(graphAddEdge g "Innsbruck" "Lauterach" 127)
(graphAddEdge g "Lauterach" "Feldkirch" 28)
(graphAddEdge g "Feldkirch" "Imst" 86)
(graphAddEdge g "Imst" "Innsbruck" 49)
(graphAddEdge g "Innsbruck" "Wörgl" 55)
(graphAddEdge g "Wörgl" "Rosenheim" 41)
(graphAddEdge g "Rosenheim" "Bad Reichenhall" 57)
(graphAddEdge g "Bad Reichenhall" "Salzburg" 15)
(graphAddEdge g "Salzburg" "Sattledt" 81)
(graphAddEdge g "Sattledt" "Linz" 31)
(graphAddEdge g "Linz" "Sankt Pölten" 99)
(graphAddEdge g "Sankt Pölten" "Vienna" 55)
(graphAddEdge g "Vienna" "Nickelsdorf" 59)
(graphAddEdge g "Nickelsdorf" "Mosonmagyaróvár" 17)
(graphAddEdge g "Mosonmagyaróvár" "Budapest" 138)
(graphAddEdge g "Budapest" "Szolnok" 94)
(graphAddEdge g "Szolnok" "Püspökladány" 71)
(graphAddEdge g "Püspökladány" "Oradea" 68)
(graphAddEdge g "Oradea" "Cluj" 130)
(graphAddEdge g "Cluj" "Napoca" 0)
(graphAddEdge g "Napoca" "Turda" 26)
(graphAddEdge g "Turda" "Târgu Mures" 59)
(graphAddEdge g "Târgu Mures" "Brasov" 128)
(graphAddEdge g "Brasov" "Ploiesti" 85)
(graphAddEdge g "Ploiesti" "Bucharest" 56)
(graphAddEdge g "Bucharest" "Urziceni" 52)
(graphAddEdge g "Urziceni" "Slobozia" 60)
(graphAddEdge g "Slobozia" "Hîrsova" 235)
(graphAddEdge g "Hîrsova" "Constanta" 290)
(graphAddEdge g "Brest" "Rennes" 210)
(graphAddEdge g "Rennes" "Le Mans" 140)
(graphAddEdge g "Le Mans" "Paris" 185)
(graphAddEdge g "Paris" "Reims" 130)
(graphAddEdge g "Reims" "Metz" 156)
(graphAddEdge g "Metz" "Saarbrücken" 61)
(graphAddEdge g "Saarbrücken" "Mannheim" 110)
(graphAddEdge g "Mannheim" "Heilbronn" 66)
(graphAddEdge g "Heilbronn" "Nuremberg" 138)
(graphAddEdge g "Nuremberg" "Rozvadov" 110)
(graphAddEdge g "Rozvadov" "Plzen" 59)
(graphAddEdge g "Plzen" "Prague" 83)
(graphAddEdge g "Prague" "Jihlava" 113)
(graphAddEdge g "Jihlava" "Brno" 77)
(graphAddEdge g "Brno" "Trencin" 110)
(graphAddEdge g "Trencin" "Prešov" 232)
(graphAddEdge g "Prešov" "Vyšné Nemecké" 83)
(graphAddEdge g "Vyšné Nemecké" "Uzhhorod" 5)
(graphAddEdge g "Uzhhorod" "Mukacheve" 36)
(graphAddEdge g "Mukacheve" "Stryj" 122)
(graphAddEdge g "Stryj" "Ternopil'" 130)
(graphAddEdge g "Ternopil'" "Khmel'nyts'kyi" 101)
(graphAddEdge g "Khmel'nyts'kyi" "Vinnytsia" 109)
(graphAddEdge g "Vinnytsia" "Uman'" 138)
(graphAddEdge g "Uman'" "Kirovohrad" 152)
(graphAddEdge g "Kirovohrad" "Dnipropetrovsk" 204)
(graphAddEdge g "Dnipropetrovsk" "Donetsk" 210)
(graphAddEdge g "Donetsk" "Rostov na Donu" 168)
(graphAddEdge g "Rostov na Donu" "Armavir" 270)
(graphAddEdge g "Armavir" "Mineralnye Vody" 181)
(graphAddEdge g "Mineralnye Vody" "Makhachkala" 377)
(graphAddEdge g "Calais" "Oostende" 79)
(graphAddEdge g "Oostende" "Brugge" 21)
(graphAddEdge g "Brugge" "Ghent" 38)
(graphAddEdge g "Ghent" "Brussels" 49)
(graphAddEdge g "Brussels" "Liège" 88)
(graphAddEdge g "Liège" "Aachen" 38)
(graphAddEdge g "Aachen" "Cologne" 645)
(graphAddEdge g "Cologne" "Olpe" 626)
(graphAddEdge g "Olpe" "Wetzlar" 70)
(graphAddEdge g "Wetzlar" "Bad Hersfeld" 91)
(graphAddEdge g "Bad Hersfeld" "Eisenach" 44)
(graphAddEdge g "Eisenach" "Erfurt" 49)
(graphAddEdge g "Erfurt" "Gera" 74)
(graphAddEdge g "Gera" "Chemnitz" 59)
(graphAddEdge g "Chemnitz" "Dresden" 61)
(graphAddEdge g "Dresden" "Görlitz" 88)
(graphAddEdge g "Görlitz" "Legnica" 81)
(graphAddEdge g "Legnica" "Wroclaw" 61)
(graphAddEdge g "Wroclaw" "Opole" 79)
(graphAddEdge g "Opole" "Gliwice" 66)
(graphAddEdge g "Gliwice" "Kraków" 94)
(graphAddEdge g "Kraków" "Przemysl" 205)
(graphAddEdge g "Przemysl" "L'viv" 90)
(graphAddEdge g "L'viv" "Rivne" 180)
(graphAddEdge g "Rivne" "Zhytomyr" 176)
(graphAddEdge g "Zhytomyr" "Kyiv" 133)
(graphAddEdge g "Kyiv" "Kharkiv" 412)
(graphAddEdge g "Kharkiv" "Luhans'k" 270)
(graphAddEdge g "Luhans'k" "Volgograd" 384)
(graphAddEdge g "Volgograd" "Astrakhan" 372)
(graphAddEdge g "Astrakhan" "Atyrau" 308)
(graphAddEdge g "Atyrau" "Beineu" 319)
(graphAddEdge g "Beineu" "Kungrad" 387)
(graphAddEdge g "Kungrad" "Nukus" 90)
(graphAddEdge g "Nukus" "Dasoguz" 75)
(graphAddEdge g "Dasoguz" "Buchara" 439)
(graphAddEdge g "Buchara" "Navoi" 89)
(graphAddEdge g "Navoi" "Samarkand" 145)
(graphAddEdge g "Samarkand" "Jizzakh" 89)
(graphAddEdge g "Jizzakh" "Tashkent" 179)
(graphAddEdge g "Tashkent" "Shymkent" 113)
(graphAddEdge g "Shymkent" "Zhambyl" 1315)
(graphAddEdge g "Zhambyl" "Bishkek" 1230)
(graphAddEdge g "Bishkek" "Almaty" 194)
(graphAddEdge g "Almaty" "Sary" 3322)
(graphAddEdge g "Sary" "Ozek" 3336)
(graphAddEdge g "Ozek" "Taldykorgan" 79)
(graphAddEdge g "Taldykorgan" "Ucharal" 237)
(graphAddEdge g "Ucharal" "Taskesken" 117)
(graphAddEdge g "Taskesken" "Ayaguz" 86)
(graphAddEdge g "Ayaguz" "Georgiyevska" 2859)
(graphAddEdge g "Georgiyevska" "Öskemen" 3003)
(graphAddEdge g "Öskemen" "Ridder" 76)
(graphAddEdge g "Hoek van Holland" "The Hague" 16)
(graphAddEdge g "The Hague" "Gouda" 28)
(graphAddEdge g "Gouda" "Utrecht" 29)
(graphAddEdge g "Utrecht" "Amersfoort" 20)
(graphAddEdge g "Amersfoort" "Oldenzaal" 104)
(graphAddEdge g "Oldenzaal" "Osnabrück" 77)
(graphAddEdge g "Osnabrück" "Bad Oeynhausen" 51)
(graphAddEdge g "Bad Oeynhausen" "Hanover" 66)
(graphAddEdge g "Hanover" "Braunschweig" 54)
(graphAddEdge g "Braunschweig" "Magdeburg" 77)
(graphAddEdge g "Magdeburg" "Berlin" 126)
(graphAddEdge g "Berlin" "Swiebodzin" 148)
(graphAddEdge g "Swiebodzin" "Poznan" 96)
(graphAddEdge g "Poznan" "Warsaw" 277)
(graphAddEdge g "Warsaw" "Brest nad Bugem" 186)
(graphAddEdge g "Brest nad Bugem" "Minsk" 325)
(graphAddEdge g "Minsk" "Smolensk" 306)
(graphAddEdge g "Smolensk" "Moscow" 369)
(graphAddEdge g "Moscow" "Ryazan" 183)
(graphAddEdge g "Ryazan" "Penza" 379)
(graphAddEdge g "Penza" "Samara" 340)
(graphAddEdge g "Samara" "Ufa" 418)
(graphAddEdge g "Ufa" "Chelyabinsk" 352)
(graphAddEdge g "Chelyabinsk" "Kurgan" 250)
(graphAddEdge g "Kurgan" "Ishim" 269)
(graphAddEdge g "Ishim" "Omsk" 275)
(graphAddEdge g "Fishguard" "Swansea" 82)
(graphAddEdge g "Swansea" "Cardiff" 55)
(graphAddEdge g "Cardiff" "Newport" 17)
(graphAddEdge g "Newport" "Bristol" 31)
(graphAddEdge g "Bristol" "London" 171)
(graphAddEdge g "London" "Colchester" 83)
(graphAddEdge g "Colchester" "Ipswich" 25)
(graphAddEdge g "Ipswich" "Felixstowe" 17)
(graphAddEdge g "Cork" "Waterford" 101)
(graphAddEdge g "Waterford" "Wexford" 45)
(graphAddEdge g "Wexford" "Rosslare" 9)
(graphAddEdge g "Tallinn" "Narva" 195)
(graphAddEdge g "Narva" "Saint Petersburg" 134)
(graphAddEdge g "Esbjerg" "Copenhagen" 260)
(graphAddEdge g "Copenhagen" "Malmö" 28)
(graphAddEdge g "Malmö" "Helsingborg" 52)
(graphAddEdge g "Helsingborg" "Halmstad" 70)
(graphAddEdge g "Halmstad" "Gothenburg" 126)
(graphAddEdge g "Gothenburg" "Örebro" 257)
(graphAddEdge g "Örebro" "Stockholm" 162)
(graphAddEdge g "Liverpool" "Manchester" 50)
(graphAddEdge g "Manchester" "Kingston upon Hull" 129)
(graphAddEdge g "Shannon" "Limerick" 17)
(graphAddEdge g "Limerick" "Dublin" 176)
(graphAddEdge g "Melbu" "Sortland" 37)
(graphAddEdge g "Sortland" "Lødingen" 42)
(graphAddEdge g "Lødingen" "Evenes" 54)
(graphAddEdge g "Evenes" "Narvik" 38)
(graphAddEdge g "Narvik" "Kiruna" 117)
(graphAddEdge g "Kiruna" "Töre" 2194)
(graphAddEdge g "Töre" "Luleå" 1951)
(graphAddEdge g "Å" "Svolvær" 707)
(graphAddEdge g "Omsk" "Pavlodar" 383)
(graphAddEdge g "Pavlodar" "Semey" 308)
(graphAddEdge g "Semey" "Georgiyevka" 2740)
(graphAddEdge g "Georgiyevka" "Maikapshagai" 2735)
(graphAddEdge g "Petropavl" "Astana" 443)
(graphAddEdge g "Astana" "Karagandy" 188)
(graphAddEdge g "Karagandy" "Balkhash" 358)
(graphAddEdge g "Balkhash" "Burubaytal" 224)
(graphAddEdge g "Burubaytal" "Almaty" 301)
(graphAddEdge g "Bishkek" "Naryn" 198)
(graphAddEdge g "Naryn" "Torugart" 105)
(graphAddEdge g "Chelyabinsk" "Kostanai" 260)
(graphAddEdge g "Kostanai" "Esil" 233)
(graphAddEdge g "Esil" "Derzhavinsk" 96)
(graphAddEdge g "Derzhavinsk" "Arkalyk" 103)
(graphAddEdge g "Arkalyk" "Zhezkazgan" 278)
(graphAddEdge g "Zhezkazgan" "Kyzylorda" 369)
(graphAddEdge g "Kyzylorda" "Shymkent" 439)
(graphAddEdge g "Tashkent" "Ayni" 222)
(graphAddEdge g "Ayni" "Dushanbe" 93)
(graphAddEdge g "Dushanbe" "Nizhniy Panj" 233)
(graphAddEdge g "Samara" "Uralsk" 236)
(graphAddEdge g "Uralsk" "Atyrau" 460)
(graphAddEdge g "Beineu" "Shetpe" 272)
(graphAddEdge g "Shetpe" "Zhetybai" 61)
(graphAddEdge g "Zhetybai" "Fetisovo" 101)
(graphAddEdge g "Fetisovo" "Bekdash" 136)
(graphAddEdge g "Bekdash" "Turkmenbashi" 174)
(graphAddEdge g "Gyzylarbat" "Border of the Islamic Republic of Iran" 223)
(graphAddEdge g "Moscow" "Tambov" 418)
(graphAddEdge g "Tambov" "Povorino" 178)
(graphAddEdge g "Povorino" "Volgograd" 321)
(graphAddEdge g "Astrakhan" "Makhachkala" 377)
(graphAddEdge g "Makhachkala" "Kuba" 198)
(graphAddEdge g "Kuba" "Baku" 155)
(graphAddEdge g "Baku" "Alyat" 1761)
(graphAddEdge g "Alyat" "Astara" 1974)
(graphAddEdge g "Mineralnye Vody" "Nalchik" 89)
(graphAddEdge g "Nalchik" "Vladikavkaz" 101)
(graphAddEdge g "Vladikavkaz" "Tbilisi" 148)
(graphAddEdge g "Tbilisi" "Yerevan" 170)
(graphAddEdge g "Yerevan" "Goris" 172)
(graphAddEdge g "Goris" "Megri" 68)
(graphAddEdge g "Yaroslavl" "Moscow" 250)
(graphAddEdge g "Moscow" "Voronezh" 467)
(graphAddEdge g "Voronezh" "Novorossijsk" 779)
(graphAddEdge g "Kirkenes" "Murmansk" 145)
(graphAddEdge g "Murmansk" "Petrozavodsk" 801)
(graphAddEdge g "Petrozavodsk" "Saint Petersburg" 301)
(graphAddEdge g "Saint Petersburg" "Moscow" 635)
(graphAddEdge g "Moscow" "Orel" 325)
(graphAddEdge g "Orel" "Kharkiv" 331)
(graphAddEdge g "Kharkiv" "Simferopol" 584)
(graphAddEdge g "Simferopol" "Alushta" 39)
(graphAddEdge g "Alushta" "Yalta" 28)
(graphAddEdge g "Moscow" "Kaluga" 162)
(graphAddEdge g "Kaluga" "Brjansk" 187)
(graphAddEdge g "Brjansk" "Glukhov" 177)
(graphAddEdge g "Glukhov" "Kyiv" 273)
(graphAddEdge g "Samsun" "Merzifon" 86)
(graphAddEdge g "Saint Petersburg" "Pskov" 262)
(graphAddEdge g "Pskov" "Homel" 621)
(graphAddEdge g "Homel" "Kyiv" 224)
(graphAddEdge g "Kyiv" "Odesa" 441)
(graphAddEdge g "Klaipeda" "Kaunas" 197)
(graphAddEdge g "Kaunas" "Vilnius" 91)
(graphAddEdge g "Vilnius" "Lida" 88)
(graphAddEdge g "Lida" "Slonim" 88)
(graphAddEdge g "Slonim" "Kobrin" 118)
(graphAddEdge g "Kobrin" "Dubno" 543)
(graphAddEdge g "Dubno" "Ternopil'" 436)
(graphAddEdge g "Ternopil'" "Chernivtsi" 143)
(graphAddEdge g "Chernivtsi" "Siret" 38)
(graphAddEdge g "Siret" "Suceava" 36)
(graphAddEdge g "Suceava" "Roman" 94)
(graphAddEdge g "Roman" "Urziceni" 247)
(graphAddEdge g "Ruse" "Byala" 183)
(graphAddEdge g "Byala" "Veliko Tarnovo" 177)
(graphAddEdge g "Veliko Tarnovo" "Stara Zagora" 73)
(graphAddEdge g "Stara Zagora" "Haskovo" 54)
(graphAddEdge g "Haskovo" "Svilengrad" 56)
(graphAddEdge g "Svilengrad" "Ormenio" 5)
(graphAddEdge g "Ormenio" "Kastanies" 23)
(graphAddEdge g "Kastanies" "Didymoteicho" 33)
(graphAddEdge g "Didymoteicho" "Alexandroupolis" 76)
(graphAddEdge g "Chaniá" "Iraklion" 102)
(graphAddEdge g "Iraklion" "Agios Nikolaos" 45)
(graphAddEdge g "Agios Nikolaos" "Sitía" 44)
(graphAddEdge g "Gdansk" "Swiecie" 105)
(graphAddEdge g "Swiecie" "Lódz" 194)
(graphAddEdge g "Lódz" "Piotrków Trybunalski" 43)
(graphAddEdge g "Piotrków Trybunalski" "Katowice" 136)
(graphAddEdge g "Katowice" "Žilina" 117)
(graphAddEdge g "Žilina" "Bratislava" 169)
(graphAddEdge g "Bratislava" "Gyor" 64)
(graphAddEdge g "Gyor" "Budapest" 107)
(graphAddEdge g "Budapest" "Szeged" 162)
(graphAddEdge g "Szeged" "Belgrade" 161)
(graphAddEdge g "Belgrade" "Niš" 202)
(graphAddEdge g "Niš" "Kumanovo" 132)
(graphAddEdge g "Kumanovo" "Skopje" 28)
(graphAddEdge g "Skopje" "Thessaloniki" 196)
(graphAddEdge g "Thessaloniki" "Larissa" 119)
(graphAddEdge g "Larissa" "Lamia" 82)
(graphAddEdge g "Lamia" "Athens" 152)
(graphAddEdge g "Vardø" "Vadsø" 45)
(graphAddEdge g "Vadsø" "Varangerbotn" 46)
(graphAddEdge g "Varangerbotn" "Utsjoki" 65)
(graphAddEdge g "Utsjoki" "Inari" 111)
(graphAddEdge g "Inari" "Ivalo" 34)
(graphAddEdge g "Ivalo" "Sodankylä" 143)
(graphAddEdge g "Sodankylä" "Rovaniemi" 109)
(graphAddEdge g "Rovaniemi" "Kemi" 99)
(graphAddEdge g "Kemi" "Oulu" 90)
(graphAddEdge g "Oulu" "Jyväskylä" 308)
(graphAddEdge g "Jyväskylä" "Heinola" 116)
(graphAddEdge g "Heinola" "Lahti" 31)
(graphAddEdge g "Lahti" "Helsinki" 98)
(graphAddEdge g "Kissamos" "Chaniá" 32)
(graphAddEdge g "Rhion" "Egion" 81)
(graphAddEdge g "Egion" "Korinthos" 81)
(graphAddEdge g "Korinthos" "Tripoli" 68)
(graphAddEdge g "Tripoli" "Kalamata" 50)
(graphAddEdge g "Swinoujscie" "Wolin" 25)
(graphAddEdge g "Wolin" "Goleniów" 34)
(graphAddEdge g "Goleniów" "Szczecin" 23)
(graphAddEdge g "Szczecin" "Gorzów Wielkopolski" 90)
(graphAddEdge g "Gorzów Wielkopolski" "Swiebodzin" 57)
(graphAddEdge g "Swiebodzin" "Zielona Góra" 34)
(graphAddEdge g "Zielona Góra" "Legnica" 93)
(graphAddEdge g "Legnica" "Jelenia Góra" 45)
(graphAddEdge g "Jelenia Góra" "Harrachov" 25)
(graphAddEdge g "Harrachov" "Železný Brod" 19)
(graphAddEdge g "Železný Brod" "Turnov" 9)
(graphAddEdge g "Turnov" "Mladá Boleslav" 26)
(graphAddEdge g "Mladá Boleslav" "Prague" 49)
(graphAddEdge g "Brno" "Bratislava" 121)
(graphAddEdge g "Bratislava" "Rajka" 18)
(graphAddEdge g "Rajka" "Csorna" 42)
(graphAddEdge g "Csorna" "Szombathely" 63)
(graphAddEdge g "Szombathely" "Zalaegerszeg" 46)
(graphAddEdge g "Zalaegerszeg" "Nagykanizsa" 44)
(graphAddEdge g "Nagykanizsa" "Letenye" 20)
(graphAddEdge g "Letenye" "Zagreb" 89)
(graphAddEdge g "Zagreb" "Karlovac" 49)
(graphAddEdge g "Karlovac" "Rijeka" 88)
(graphAddEdge g "Rijeka" "Split" 257)
(graphAddEdge g "Split" "Dubrovnik" 165)
(graphAddEdge g "Dubrovnik" "Petrovac" 306)
(graphAddEdge g "Petrovac" "Podgorica" 218)
(graphAddEdge g "Podgorica" "Bijelo Polje" 76)
(graphAddEdge g "Bijelo Polje" "Skopje" 180)
(graphAddEdge g "Skopje" "Kicevo" 66)
(graphAddEdge g "Kicevo" "Ohrid" 46)
(graphAddEdge g "Ohrid" "Bitola" 46)
(graphAddEdge g "Bitola" "Niki" 15)
(graphAddEdge g "Niki" "Vevi" 22)
(graphAddEdge g "Vevi" "Kozani" 53)
(graphAddEdge g "Kozani" "Larissa" 91)
(graphAddEdge g "Larissa" "Domokos" 878)
(graphAddEdge g "Domokos" "Lamia" 959)
(graphAddEdge g "Lamia" "Brallos" 21)
(graphAddEdge g "Brallos" "Itea" 31)
(graphAddEdge g "Itea" "Antirrion" 58)
(graphAddEdge g "Malmö" "Ystad" 55)
(graphAddEdge g "Igoumenitsa" "Preveza" 73)
(graphAddEdge g "Preveza" "Rhion" 70)
(graphAddEdge g "Rhion" "Patrai" 69)
(graphAddEdge g "Patrai" "Pyrgos" 68)
(graphAddEdge g "Pyrgos" "Kalamáta" 89)
(graphAddEdge g "Rostock" "Berlin" 194)
(graphAddEdge g "Berlin" "Lübbenau" 82)
(graphAddEdge g "Lübbenau" "Dresden" 92)
(graphAddEdge g "Dresden" "Teplice" 45)
(graphAddEdge g "Teplice" "Prague" 74)
(graphAddEdge g "Prague" "Tábor" 76)
(graphAddEdge g "Tábor" "Linz" 126)
(graphAddEdge g "Linz" "Salzburg" 108)
(graphAddEdge g "Salzburg" "Villach" 144)
(graphAddEdge g "Villach" "Tarvisio" 24)
(graphAddEdge g "Tarvisio" "Udine" 55)
(graphAddEdge g "Udine" "Palmanova" 18)
(graphAddEdge g "Mestre" "Ravenna" 120)
(graphAddEdge g "Ravenna" "Cesena" 31)
(graphAddEdge g "Cesena" "Rimini" 27)
(graphAddEdge g "Rimini" "Fano" 43)
(graphAddEdge g "Fano" "Ancona" 47)
(graphAddEdge g "Ancona" "Pescara" 139)
(graphAddEdge g "Pescara" "Canosa" 384)
(graphAddEdge g "Canosa" "Bari" 649)
(graphAddEdge g "Bari" "Brindisi" 106)
(graphAddEdge g "Helsingør" "Copenhagen" 38)
(graphAddEdge g "Copenhagen" "Køge" 35)
(graphAddEdge g "Køge" "Vordingborg" 52)
(graphAddEdge g "Vordingborg" "Farø" 8)
(graphAddEdge g "Farø" "Nykøbing Falster" 22)
(graphAddEdge g "Nykøbing Falster" "Gedser" 21)
(graphAddEdge g "Messina" "Catania" 87)
(graphAddEdge g "Catania" "Siracusa" 51)
(graphAddEdge g "Siracusa" "Gela" 92)
(graphAddEdge g "Fredrikshavn" "Aalborg" 57)
(graphAddEdge g "Aalborg" "Århus" 101)
(graphAddEdge g "Århus" "Vejle" 65)
(graphAddEdge g "Vejle" "Kolding" 23)
(graphAddEdge g "Kolding" "Frøslev" 180)
(graphAddEdge g "Frøslev" "Flensburg" 192)
(graphAddEdge g "Flensburg" "Hamburg" 142)
(graphAddEdge g "Hamburg" "Hanover" 132)
(graphAddEdge g "Hanover" "Göttingen" 94)
(graphAddEdge g "Göttingen" "Kassel" 526)
(graphAddEdge g "Kassel" "Fulda" 507)
(graphAddEdge g "Fulda" "Würzburg" 86)
(graphAddEdge g "Würzburg" "Nuremberg" 90)
(graphAddEdge g "Nuremberg" "Munich" 151)
(graphAddEdge g "Munich" "Rosenheim" 51)
(graphAddEdge g "Innsbruck" "Brenner" 30)
(graphAddEdge g "Brenner" "Fortezza" 25)
(graphAddEdge g "Fortezza" "Bozen" 37)
(graphAddEdge g "Bozen" "Trento" 51)
(graphAddEdge g "Trento" "Verona" 70)
(graphAddEdge g "Verona" "Modena" 88)
(graphAddEdge g "Modena" "Bologna" 37)
(graphAddEdge g "Bologna" "Cesena" 81)
(graphAddEdge g "Cesena" "Perugia" 114)
(graphAddEdge g "Perugia" "Fiano" 453)
(graphAddEdge g "Fiano" "Naples" 732)
(graphAddEdge g "Naples" "Salerno" 46)
(graphAddEdge g "Salerno" "Sicignano" 47)
(graphAddEdge g "Sicignano" "Cosenza" 160)
(graphAddEdge g "Cosenza" "Villa San Giovanni" 132)
(graphAddEdge g "Amsterdam" "Utrecht" 36)
(graphAddEdge g "Utrecht" "Arnhem" 51)
(graphAddEdge g "Arnhem" "Emmerich" 31)
(graphAddEdge g "Emmerich" "Oberhausen" 58)
(graphAddEdge g "Oberhausen" "Cologne" 693)
(graphAddEdge g "Cologne" "Frankfurt am Main" 512)
(graphAddEdge g "Frankfurt am Main" "Heidelberg" 78)
(graphAddEdge g "Heidelberg" "Karlsruhe" 218)
(graphAddEdge g "Karlsruhe" "Offenburg" 302)
(graphAddEdge g "Offenburg" "Basel" 105)
(graphAddEdge g "Basel" "Olten" 33)
(graphAddEdge g "Olten" "Lucerne" 44)
(graphAddEdge g "Lucerne" "Altdorf" 173)
(graphAddEdge g "Altdorf" "San Gottardo" 317)
(graphAddEdge g "San Gottardo" "Bellinzona" 112)
(graphAddEdge g "Bellinzona" "Lugano" 21)
(graphAddEdge g "Lugano" "Chiasso" 19)
(graphAddEdge g "Chiasso" "Como" 5)
(graphAddEdge g "Como" "Milan" 39)
(graphAddEdge g "Milan" "Piacenza" 60)
(graphAddEdge g "Piacenza" "Parma" 57)
(graphAddEdge g "Parma" "Modena" 50)
(graphAddEdge g "Modena" "Florence" 101)
(graphAddEdge g "Florence" "Rome" 231)
(graphAddEdge g "Porto Torres" "Sassari" 18)
(graphAddEdge g "Sassari" "Cagliari" 174)
(graphAddEdge g "Bastia" "Porto Vecchio" 124)
(graphAddEdge g "Porto Vecchio" "Bonifacio" 24)
(graphAddEdge g "Hoek van Holland" "Rotterdam" 23)
(graphAddEdge g "Rotterdam" "Eindhoven" 87)
(graphAddEdge g "Eindhoven" "Maastricht" 66)
(graphAddEdge g "Maastricht" "Liège" 25)
(graphAddEdge g "Liège" "Bastogne" 72)
(graphAddEdge g "Bastogne" "Arlon" 36)
(graphAddEdge g "Arlon" "Luxembourg" 269)
(graphAddEdge g "Luxembourg" "Metz" 282)
(graphAddEdge g "Metz" "Saint Avold" 38)
(graphAddEdge g "Saint Avold" "Strasbourg" 95)
(graphAddEdge g "Strasbourg" "Mulhouse" 97)
(graphAddEdge g "Olten" "Berne" 54)
(graphAddEdge g "Berne" "Lausanne" 78)
(graphAddEdge g "Lausanne" "Geneva" 51)
(graphAddEdge g "Geneva" "Mont Blanc" 83)
(graphAddEdge g "Mont Blanc" "Aosta" 178)
(graphAddEdge g "Aosta" "Ivrea" 52)
(graphAddEdge g "Ivrea" "Vercelli" 45)
(graphAddEdge g "Vercelli" "Alessandria" 48)
(graphAddEdge g "Alessandria" "Genova" 61)
(graphAddEdge g "Calais" "Paris" 235)
(graphAddEdge g "Paris" "Lyon" 392)
(graphAddEdge g "Lyon" "Orange" 180)
(graphAddEdge g "Orange" "Narbonne" 179)
(graphAddEdge g "Narbonne" "Girona" 134)
(graphAddEdge g "Girona" "Barcelona" 85)
(graphAddEdge g "Barcelona" "Tarragona" 82)
(graphAddEdge g "Tarragona" "Castellón de la Plana" 166)
(graphAddEdge g "Castellón de la Plana" "Valencia" 64)
(graphAddEdge g "Valencia" "Alicante" 124)
(graphAddEdge g "Alicante" "Murcia" 68)
(graphAddEdge g "Murcia" "Almería" 174)
(graphAddEdge g "Almería" "Málaga" 175)
(graphAddEdge g "Málaga" "Algeciras" 113)
(graphAddEdge g "Inverness" "Perth" 130)
(graphAddEdge g "Perth" "Edinburgh" 51)
(graphAddEdge g "Edinburgh" "Newcastle" 147)
(graphAddEdge g "Newcastle" "London" 398)
(graphAddEdge g "London" "Folkestone" 101)
(graphAddEdge g "Folkestone" "Dover" 10)
(graphAddEdge g "Le Havre" "Paris" 178)
(graphAddEdge g "Paris" "Orléans" 110)
(graphAddEdge g "Orléans" "Bordeaux" 390)
(graphAddEdge g "Bordeaux" "San Sebastian" 202)
(graphAddEdge g "San Sebastian" "Madrid" 353)
(graphAddEdge g "Madrid" "Sevilla" 391)
(graphAddEdge g "Sevilla" "Algeciras" 148)
(graphAddEdge g "Greenock" "Glasgow" 33)
(graphAddEdge g "Glasgow" "Preston" 254)
(graphAddEdge g "Preston" "Birmingham" 152)
(graphAddEdge g "Birmingham" "Southampton" 178)

;; dijkstra CALLING PART TO CALCULATE DISTANCE
;; WITHOUT WEIGHTS
(println "Alessandria - Prague / without weights")
(println (dijkstra g "Alessandria" "Prague" true))
(newline)
(println "Catania - Prague / without weights")
(println (dijkstra g "Catania" "Prague" true))

(newline)

;; dijkstra CALLING PART TO CALCULATE DISTANCE
;; USING WEIGHTS
(println "Alessandria - Prague / with weights")
(println (dijkstra g "Alessandria" "Prague"))
(newline)
(println "Catania - Prague / with weights")
(println (dijkstra g "Catania" "Prague"))
