(def g (makeGraph))
(graphAddVertex g "Hîrsova")
(graphAddVertex g "Baku")
(graphAddVertex g "Samara")
(graphAddVertex g "Ormenio")
(graphAddVertex g "Napoca")
(graphAddVertex g "Orel")
(graphAddVertex g "Makhachkala")
(graphAddVertex g "Ystad")
(graphAddVertex g "Gedser")
(graphAddVertex g "Bad Hersfeld")
(graphAddVertex g "Copenhagen")
(graphAddVertex g "Opole")
(graphAddVertex g "Rhion")
(graphAddVertex g "Bishkek")
(graphAddVertex g "Tarvisio")
(graphAddVertex g "Sassari")
(graphAddVertex g "Göttingen")
(graphAddVertex g "Örebro")
(graphAddVertex g "Brno")
(graphAddVertex g "Oulu")
(graphAddVertex g "Kissamos")
(graphAddVertex g "Berlin")
(graphAddVertex g "Goleniów")
(graphAddVertex g "Heinola")
(graphAddVertex g "Ioannina")
(graphAddVertex g "Jelenia Góra")
(graphAddVertex g "Beaune")
(graphAddVertex g "Jizzakh")
(graphAddVertex g "Villach")
(graphAddVertex g "Omsk")
(graphAddVertex g "Nusaybin")
(graphAddVertex g "Slonim")
(graphAddVertex g "Udine")
(graphAddVertex g "Yerevan")
(graphAddVertex g "Khmel'nyts'kyi")
(graphAddVertex g "Ohrid")
(graphAddVertex g "Dubrovnik")
(graphAddVertex g "Genova")
(graphAddVertex g "Kirovohrad")
(graphAddVertex g "Lødingen")
(graphAddVertex g "Yalta")
(graphAddVertex g "Kozani")
(graphAddVertex g "Folkestone")
(graphAddVertex g "Simferopol")
(graphAddVertex g "Ravenna")
(graphAddVertex g "Petrovac")
(graphAddVertex g "Rostov na Donu")
(graphAddVertex g "Buchara")
(graphAddVertex g "Lódz")
(graphAddVertex g "Wroclaw")
(graphAddVertex g "Imst")
(graphAddVertex g "St. Margrethen")
(graphAddVertex g "Nykøbing Falster")
(graphAddVertex g "Dublin")
(graphAddVertex g "Podgorica")
(graphAddVertex g "Fulda")
(graphAddVertex g "Habur")
(graphAddVertex g "Kraków")
(graphAddVertex g "Korinthos")
(graphAddVertex g "Frøslev")
(graphAddVertex g "Paris")
(graphAddVertex g "Ferrand")
(graphAddVertex g "Vilnius")
(graphAddVertex g "Siret")
(graphAddVertex g "Trieste")
(graphAddVertex g "Rimini")
(graphAddVertex g "Balkhash")
(graphAddVertex g "Uzhhorod")
(graphAddVertex g "Catania")
(graphAddVertex g "Rovaniemi")
(graphAddVertex g "Trento")
(graphAddVertex g "Astana")
(graphAddVertex g "Warsaw")
(graphAddVertex g "Vrsac")
(graphAddVertex g "Volgograd")
(graphAddVertex g "Amsterdam")
(graphAddVertex g "Postojna")
(graphAddVertex g "Plzen")
(graphAddVertex g "Bekdash")
(graphAddVertex g "Brugge")
(graphAddVertex g "Berne")
(graphAddVertex g "Ridder")
(graphAddVertex g "Turnu Severin")
(graphAddVertex g "Bellinzona")
(graphAddVertex g "Farø")
(graphAddVertex g "Rijeka")
(graphAddVertex g "Palermo")
(graphAddVertex g "Prešov")
(graphAddVertex g "Eisenach")
(graphAddVertex g "Rennes")
(graphAddVertex g "Esbjerg")
(graphAddVertex g "Mukacheve")
(graphAddVertex g "Cluj")
(graphAddVertex g "San Sebastián")
(graphAddVertex g "Taranto")
(graphAddVertex g "Jihlava")
(graphAddVertex g "Nizhniy Panj")
(graphAddVertex g "Karagandy")
(graphAddVertex g "Lamia")
(graphAddVertex g "Chambéry")
(graphAddVertex g "Astara")
(graphAddVertex g "Niki")
(graphAddVertex g "Murcia")
(graphAddVertex g "Brjansk")
(graphAddVertex g "Batumi")
(graphAddVertex g "Zielona Góra")
(graphAddVertex g "Limerick")
(graphAddVertex g "Ipswich")
(graphAddVertex g "Rosenheim")
(graphAddVertex g "Lübbenau")
(graphAddVertex g "Kurgan")
(graphAddVertex g "Å")
(graphAddVertex g "Pavlodar")
(graphAddVertex g "Cardiff")
(graphAddVertex g "Suceava")
(graphAddVertex g "Lorient")
(graphAddVertex g "Egion")
(graphAddVertex g "Kaunas")
(graphAddVertex g "Vejle")
(graphAddVertex g "Vercelli")
(graphAddVertex g "Metaponto")
(graphAddVertex g "Târgu Mures")
(graphAddVertex g "Tripoli")
(graphAddVertex g "Sicignano")
(graphAddVertex g "Razgrad")
(graphAddVertex g "Metz")
(graphAddVertex g "Bonifacio")
(graphAddVertex g "Kicevo")
(graphAddVertex g "Alexandroupolis")
(graphAddVertex g "Povorino")
(graphAddVertex g "Novorossijsk")
(graphAddVertex g "Kirkenes")
(graphAddVertex g "Sary Tash")
(graphAddVertex g "Iraklion")
(graphAddVertex g "Swiecie")
(graphAddVertex g "Dubno")
(graphAddVertex g "Uralsk")
(graphAddVertex g "Ryazan")
(graphAddVertex g "Skopje")
(graphAddVertex g "Chaniá")
(graphAddVertex g "Mont Blanc")
(graphAddVertex g "Landeck")
(graphAddVertex g "Bastia")
(graphAddVertex g "Helsingborg")
(graphAddVertex g "Ganca")
(graphAddVertex g "Zhambyl")
(graphAddVertex g "Geneva")
(graphAddVertex g "Ivalo")
(graphAddVertex g "Tours")
(graphAddVertex g "Moscow")
(graphAddVertex g "Gerede")
(graphAddVertex g "Stryj")
(graphAddVertex g "Lisbon")
(graphAddVertex g "Valencia")
(graphAddVertex g "Lyon")
(graphAddVertex g "Århus")
(graphAddVertex g "Castellón de la Plana")
(graphAddVertex g "Utrecht")
(graphAddVertex g "Telfs")
(graphAddVertex g "Dnipropetrovsk")
(graphAddVertex g "Bregenz")
(graphAddVertex g "Veliko Tarnovo")
(graphAddVertex g "Bursa")
(graphAddVertex g "Hamburg")
(graphAddVertex g "Alushta")
(graphAddVertex g "Dole")
(graphAddVertex g "Inari")
(graphAddVertex g "Alat")
(graphAddVertex g "Murmansk")
(graphAddVertex g "Izmir")
(graphAddVertex g "Roman")
(graphAddVertex g "Samsun")
(graphAddVertex g "Voronezh")
(graphAddVertex g "Saint Petersburg")
(graphAddVertex g "Modena")
(graphAddVertex g "Fiano")
(graphAddVertex g "Ucharal")
(graphAddVertex g "Vardø")
(graphAddVertex g "Karshi")
(graphAddVertex g "Tábor")
(graphAddVertex g "Lida")
(graphAddVertex g "Linz")
(graphAddVertex g "Püspökladány")
(graphAddVertex g "Kharkiv")
(graphAddVertex g "Malmö")
(graphAddVertex g "Patrai")
(graphAddVertex g "Málaga")
(graphAddVertex g "Preston")
(graphAddVertex g "Vienna")
(graphAddVertex g "Kiruna")
(graphAddVertex g "Orléans")
(graphAddVertex g "Budapest")
(graphAddVertex g "Žilina")
(graphAddVertex g "Messina")
(graphAddVertex g "Chernivtsi")
(graphAddVertex g "Ufa")
(graphAddVertex g "Rajka")
(graphAddVertex g "Uman'")
(graphAddVertex g "Montargis")
(graphAddVertex g "Olpe")
(graphAddVertex g "Swinoujscie")
(graphAddVertex g "Cosenza")
(graphAddVertex g "Drobeta")
(graphAddVertex g "Chelyabinsk")
(graphAddVertex g "Innsbruck")
(graphAddVertex g "Birmingham")
(graphAddVertex g "Gothenburg")
(graphAddVertex g "Rivne")
(graphAddVertex g "San Sebastian")
(graphAddVertex g "Luleå")
(graphAddVertex g "Mosonmagyaróvár")
(graphAddVertex g "Ljubljana")
(graphAddVertex g "Kalamata")
(graphAddVertex g "Szczecin")
(graphAddVertex g "Girona")
(graphAddVertex g "Almería")
(graphAddVertex g "Donetsk")
(graphAddVertex g "Villa San Giovanni")
(graphAddVertex g "Greenock")
(graphAddVertex g "Porto Vecchio")
(graphAddVertex g "Emmerich")
(graphAddVertex g "Split")
(graphAddVertex g "Odesa")
(graphAddVertex g "Vordingborg")
(graphAddVertex g "Legnica")
(graphAddVertex g "Alexandria")
(graphAddVertex g "Pescara")
(graphAddVertex g "Heidelberg")
(graphAddVertex g "London")
(graphAddVertex g "Würzburg")
(graphAddVertex g "Khashuri")
(graphAddVertex g "Bozen")
(graphAddVertex g "Bucharest")
(graphAddVertex g "Helsingør")
(graphAddVertex g "Nuremberg")
(graphAddVertex g "Southampton")
(graphAddVertex g "San Gottardo")
(graphAddVertex g "Lauterach")
(graphAddVertex g "Orange")
(graphAddVertex g "Osnabrück")
(graphAddVertex g "Kassel")
(graphAddVertex g "Navoi")
(graphAddVertex g "Sattledt")
(graphAddVertex g "Alicante")
(graphAddVertex g "Bad Oeynhausen")
(graphAddVertex g "Sevilla")
(graphAddVertex g "Jirgatal")
(graphAddVertex g "Priština")
(graphAddVertex g "Rotterdam")
(graphAddVertex g "Vyšné Nemecké")
(graphAddVertex g "Urziceni")
(graphAddVertex g "Bristol")
(graphAddVertex g "Melbu")
(graphAddVertex g "Winterthur")
(graphAddVertex g "Strasbourg")
(graphAddVertex g "Craiova")
(graphAddVertex g "Jyväskylä")
(graphAddVertex g "Fano")
(graphAddVertex g "Mannheim")
(graphAddVertex g "Rozvadov")
(graphAddVertex g "Porto Torres")
(graphAddVertex g "Felixstowe")
(graphAddVertex g "Teplice")
(graphAddVertex g "Kyzylorda")
(graphAddVertex g "Tortona")
(graphAddVertex g "Karlsruhe")
(graphAddVertex g "Shoumen")
(graphAddVertex g "Ordu")
(graphAddVertex g "Ternopil'")
(graphAddVertex g "Brallos")
(graphAddVertex g "Ankara")
(graphAddVertex g "Zürich")
(graphAddVertex g "Utsjoki")
(graphAddVertex g "Ayaguz")
(graphAddVertex g "Swansea")
(graphAddVertex g "Semey")
(graphAddVertex g "Alessandria")
(graphAddVertex g "Newport")
(graphAddVertex g "Ishim")
(graphAddVertex g "Rome")
(graphAddVertex g "Turda")
(graphAddVertex g "Hanover")
(graphAddVertex g "Naryn")
(graphAddVertex g "Georgiyevka")
(graphAddVertex g "Yaroslavl")
(graphAddVertex g "Amasya")
(graphAddVertex g "Erfurt")
(graphAddVertex g "Klaipeda")
(graphAddVertex g "Bologna")
(graphAddVertex g "Tambov")
(graphAddVertex g "Antirrion")
(graphAddVertex g "Salerno")
(graphAddVertex g "Florence")
(graphAddVertex g "Ayni")
(graphAddVertex g "Varangerbotn")
(graphAddVertex g "Gyzylarbat")
(graphAddVertex g "St. Gallen")
(graphAddVertex g "L'viv")
(graphAddVertex g "Nice")
(graphAddVertex g "Chardzhu")
(graphAddVertex g "Reims")
(graphAddVertex g "Homel")
(graphAddVertex g "Gürbulak")
(graphAddVertex g "Oradea")
(graphAddVertex g "Frankfurt am Main")
(graphAddVertex g "Arkalyk")
(graphAddVertex g "Angers")
(graphAddVertex g "Sofia")
(graphAddVertex g "Fortezza")
(graphAddVertex g "Kuba")
(graphAddVertex g "Manchester")
(graphAddVertex g "Shymkent")
(graphAddVertex g "Slobozia")
(graphAddVertex g "Tallinn")
(graphAddVertex g "Edinburgh")
(graphAddVertex g "Ruse")
(graphAddVertex g "Fetisovo")
(graphAddVertex g "Oostende")
(graphAddVertex g "Zalaegerszeg")
(graphAddVertex g "Luxembourg")
(graphAddVertex g "Mulhouse")
(graphAddVertex g "Saarbrücken")
(graphAddVertex g "Heilbronn")
(graphAddVertex g "Bratislava")
(graphAddVertex g "Sodankylä")
(graphAddVertex g "Katowice")
(graphAddVertex g "Ivrea")
(graphAddVertex g "Ghent")
(graphAddVertex g "Mineralnye Vody")
(graphAddVertex g "Amersfoort")
(graphAddVertex g "Arnhem")
(graphAddVertex g "The Hague")
(graphAddVertex g "Bijelo Polje")
(graphAddVertex g "Harrachov")
(graphAddVertex g "Esil")
(graphAddVertex g "Gelibolu")
(graphAddVertex g "Sitía")
(graphAddVertex g "Cagliari")
(graphAddVertex g "Alyat")
(graphAddVertex g "Braunschweig")
(graphAddVertex g "Železný Brod")
(graphAddVertex g "Køge")
(graphAddVertex g "Lucerne")
(graphAddVertex g "Pyrgos")
(graphAddVertex g "Zhetybai")
(graphAddVertex g "Letenye")
(graphAddVertex g "Dushanbe")
(graphAddVertex g "Nalchik")
(graphAddVertex g "Szombathely")
(graphAddVertex g "Torugart")
(graphAddVertex g "Shetpe")
(graphAddVertex g "Liverpool")
(graphAddVertex g "Szolnok")
(graphAddVertex g "Ploiesti")
(graphAddVertex g "Saint")
(graphAddVertex g "Aachen")
(graphAddVertex g "Fishguard")
(graphAddVertex g "Feldkirch")
(graphAddVertex g "Liège")
(graphAddVertex g "Gela")
(graphAddVertex g "Prague")
(graphAddVertex g "Csorna")
(graphAddVertex g "Istanbul")
(graphAddVertex g "Le Mans")
(graphAddVertex g "Madrid")
(graphAddVertex g "Rosslare")
(graphAddVertex g "Görlitz")
(graphAddVertex g "Verona")
(graphAddVertex g "Como")
(graphAddVertex g "Evenes")
(graphAddVertex g "Kobrin")
(graphAddVertex g "Karlovac")
(graphAddVertex g "Fredrikshavn")
(graphAddVertex g "Luhans'k")
(graphAddVertex g "Armavir")
(graphAddVertex g "Domokos")
(graphAddVertex g "Kolding")
(graphAddVertex g "Newcastle")
(graphAddVertex g "Dresden")
(graphAddVertex g "Aalborg")
(graphAddVertex g "Canosa")
(graphAddVertex g "Olten")
(graphAddVertex g "Kemi")
(graphAddVertex g "Szeged")
(graphAddVertex g "Minsk")
(graphAddVertex g "Cologne")
(graphAddVertex g "Perth")
(graphAddVertex g "Wolin")
(graphAddVertex g "Athens")
(graphAddVertex g "Parma")
(graphAddVertex g "Belgrade")
(graphAddVertex g "A Coruña")
(graphAddVertex g "Guzai")
(graphAddVertex g "Buonfornello")
(graphAddVertex g "Glukhov")
(graphAddVertex g "Sortland")
(graphAddVertex g "Samarkand")
(graphAddVertex g "Nagykanizsa")
(graphAddVertex g "Töre")
(graphAddVertex g "Piotrków Trybunalski")
(graphAddVertex g "Islamic Republic of Iran")
(graphAddVertex g "Megri")
(graphAddVertex g "Svolvær")
(graphAddVertex g "Turin")
(graphAddVertex g "Altdorf")
(graphAddVertex g "Kastanies")
(graphAddVertex g "Stockholm")
(graphAddVertex g "Goris")
(graphAddVertex g "Aosta")
(graphAddVertex g "Lugano")
(graphAddVertex g "Narva")
(graphAddVertex g "Bilbao")
(graphAddVertex g "Kalamáta")
(graphAddVertex g "Gyor")
(graphAddVertex g "Besançon")
(graphAddVertex g "Bitola")
(graphAddVertex g "Border of the Islamic Republic of Iran")
(graphAddVertex g "Chemnitz")
(graphAddVertex g "Vladikavkaz")
(graphAddVertex g "Colchester")
(graphAddVertex g "Clermont")
(graphAddVertex g "Atyrau")
(graphAddVertex g "Beineu")
(graphAddVertex g "Mladá Boleslav")
(graphAddVertex g "Merzifon")
(graphAddVertex g "Gliwice")
(graphAddVertex g "Nukus")
(graphAddVertex g "Mazara del Vallo")
(graphAddVertex g "Barcelona")
(graphAddVertex g "Bordeaux")
(graphAddVertex g "Siracusa")
(graphAddVertex g "Vadsø")
(graphAddVertex g "Giurgiu")
(graphAddVertex g "Salzburg")
(graphAddVertex g "Reggio di Calabria")
(graphAddVertex g "Giresun")
(graphAddVertex g "Halmstad")
(graphAddVertex g "Milan")
(graphAddVertex g "Magdeburg")
(graphAddVertex g "Narvik")
(graphAddVertex g "Lahti")
(graphAddVertex g "Erzurum")
(graphAddVertex g "Lausanne")
(graphAddVertex g "Sherobod")
(graphAddVertex g "Dover")
(graphAddVertex g "Dasoguz")
(graphAddVertex g "Evlak")
(graphAddVertex g "Wexford")
(graphAddVertex g "Larissa")
(graphAddVertex g "Munich")
(graphAddVertex g "Zhezkazgan")
(graphAddVertex g "Kostanai")
(graphAddVertex g "Adana")
(graphAddVertex g "Brussels")
(graphAddVertex g "Stara Zagora")
(graphAddVertex g "Tedjen")
(graphAddVertex g "Narbonne")
(graphAddVertex g "Georgiyevska")
(graphAddVertex g "Sary")
(graphAddVertex g "Vinnytsia")
(graphAddVertex g "Almaty")
(graphAddVertex g "Susa")
(graphAddVertex g "Tbilisi")
(graphAddVertex g "Glasgow")
(graphAddVertex g "Eindhoven")
(graphAddVertex g "Flensburg")
(graphAddVertex g "Cork")
(graphAddVertex g "Varna")
(graphAddVertex g "Constanta")
(graphAddVertex g "Wörgl")
(graphAddVertex g "Kungrad")
(graphAddVertex g "Preveza")
(graphAddVertex g "Gouda")
(graphAddVertex g "Tarragona")
(graphAddVertex g "Maikapshagai")
(graphAddVertex g "Poti")
(graphAddVertex g "Zagreb")
(graphAddVertex g "Kumanovo")
(graphAddVertex g "Trencin")
(graphAddVertex g "Algeciras")
(graphAddVertex g "Samtredia")
(graphAddVertex g "Bad Reichenhall")
(graphAddVertex g "Vevi")
(graphAddVertex g "Gera")
(graphAddVertex g "Arlon")
(graphAddVertex g "Pskov")
(graphAddVertex g "Helsinki")
(graphAddVertex g "Waterford")
(graphAddVertex g "Offenburg")
(graphAddVertex g "Petropavl")
(graphAddVertex g "Irkeshtam")
(graphAddVertex g "Agios Nikolaos")
(graphAddVertex g "Brescia")
(graphAddVertex g "Brindisi")
(graphAddVertex g "Rostock")
(graphAddVertex g "Didymoteicho")
(graphAddVertex g "Slavonski Brod")
(graphAddVertex g "Igoumenitsa")
(graphAddVertex g "Haskovo")
(graphAddVertex g "Auxerre")
(graphAddVertex g "Petrozavodsk")
(graphAddVertex g "Chiasso")
(graphAddVertex g "Calais")
(graphAddVertex g "Ozek")
(graphAddVertex g "Smolensk")
(graphAddVertex g "Le Havre")
(graphAddVertex g "Cesena")
(graphAddVertex g "Palmanova")
(graphAddVertex g "Mestre")
(graphAddVertex g "Tashkent")
(graphAddVertex g "Nickelsdorf")
(graphAddVertex g "Belfort")
(graphAddVertex g "Hoek van Holland")
(graphAddVertex g "Bari")
(graphAddVertex g "Piacenza")
(graphAddVertex g "Taldykorgan")
(graphAddVertex g "Sankt Pölten")
(graphAddVertex g "Penza")
(graphAddVertex g "Swiebodzin")
(graphAddVertex g "Nantes")
(graphAddVertex g "Timisoara")
(graphAddVertex g "Svilengrad")
(graphAddVertex g "Ashgabat")
(graphAddVertex g "Iraq")
(graphAddVertex g "Maastricht")
(graphAddVertex g "Termis")
(graphAddVertex g "Kingston upon Hull")
(graphAddVertex g "Brest")
(graphAddVertex g "Vannes")
(graphAddVertex g "Trabzon")
(graphAddVertex g "Ancona")
(graphAddVertex g "Oldenzaal")
(graphAddVertex g "Avold")
(graphAddVertex g "Burubaytal")
(graphAddVertex g "Astrakhan")
(graphAddVertex g "Niš")
(graphAddVertex g "Oberhausen")
(graphAddVertex g "Shannon")
(graphAddVertex g "Naples")
(graphAddVertex g "Przemysl")
(graphAddVertex g "Brenner")
(graphAddVertex g "Öskemen")
(graphAddVertex g "Basel")
(graphAddVertex g "Bastogne")
(graphAddVertex g "Thessaloniki")
(graphAddVertex g "Kaluga")
(graphAddVertex g "Derzhavinsk")
(graphAddVertex g "Mary")
(graphAddVertex g "Kyiv")
(graphAddVertex g "Zhytomyr")
(graphAddVertex g "Turnov")
(graphAddVertex g "Poznan")
(graphAddVertex g "Gorzów Wielkopolski")
(graphAddVertex g "Inverness")
(graphAddVertex g "Taskesken")
(graphAddVertex g "Byala")
(graphAddVertex g "Perugia")
(graphAddVertex g "Turkmenbashi")
(graphAddVertex g "Brasov")
(graphAddVertex g "Lapseki")
(graphAddVertex g "Toulouse")
(graphAddVertex g "Itea")
(graphAddVertex g "Wetzlar")
(graphAddVertex g "Gdansk")
(graphAddEdge g "Lapseki" "Bursa")
(graphAddEdge g "Bursa" "Ankara")
(graphAddEdge g "Ankara" "Adana")
(graphAddEdge g "Adana" "Nusaybin")
(graphAddEdge g "Nusaybin" "Habur")
(graphAddEdge g "Habur" "Iraq")
(graphAddEdge g "Igoumenitsa" "Ioannina")
(graphAddEdge g "Ioannina" "Thessaloniki")
(graphAddEdge g "Thessaloniki" "Alexandroupolis")
(graphAddEdge g "Alexandroupolis" "Gelibolu")
(graphAddEdge g "Reggio di Calabria" "Metaponto")
(graphAddEdge g "Metaponto" "Taranto")
(graphAddEdge g "Taranto" "Brindisi")
(graphAddEdge g "Mazara del Vallo" "Palermo")
(graphAddEdge g "Palermo" "Buonfornello")
(graphAddEdge g "Buonfornello" "Messina")
(graphAddEdge g "Lisbon" "Madrid")
(graphAddEdge g "Madrid" "Barcelona")
(graphAddEdge g "Dubrovnik" "Priština")
(graphAddEdge g "Priština" "Sofia")
(graphAddEdge g "Sofia" "Istanbul")
(graphAddEdge g "Istanbul" "Izmir")
(graphAddEdge g "Izmir" "Gerede")
(graphAddEdge g "Gerede" "Amasya")
(graphAddEdge g "Amasya" "Erzurum")
(graphAddEdge g "Erzurum" "Gürbulak")
(graphAddEdge g "Gürbulak" "Islamic Republic of Iran")
(graphAddEdge g "Lisbon" "San Sebastián")
(graphAddEdge g "San Sebastián" "Toulouse")
(graphAddEdge g "Toulouse" "Nice")
(graphAddEdge g "Nice" "Genova")
(graphAddEdge g "Genova" "Rome")
(graphAddEdge g "Rome" "Pescara")
(graphAddEdge g "Samsun" "Ordu")
(graphAddEdge g "Ordu" "Giresun")
(graphAddEdge g "Giresun" "Trabzon")
(graphAddEdge g "Trabzon" "Batumi")
(graphAddEdge g "Batumi" "Poti")
(graphAddEdge g "A Coruña" "Bilbao")
(graphAddEdge g "Bilbao" "San Sebastián")
(graphAddEdge g "San Sebastián" "Bordeaux")
(graphAddEdge g "Bordeaux" "Clermont")
(graphAddEdge g "Clermont" "Ferrand")
(graphAddEdge g "Ferrand" "Lyon")
(graphAddEdge g "Lyon" "Chambéry")
(graphAddEdge g "Chambéry" "Susa")
(graphAddEdge g "Susa" "Turin")
(graphAddEdge g "Turin" "Alessandria")
(graphAddEdge g "Alessandria" "Tortona")
(graphAddEdge g "Tortona" "Brescia")
(graphAddEdge g "Brescia" "Verona")
(graphAddEdge g "Verona" "Mestre")
(graphAddEdge g "Mestre" "Palmanova")
(graphAddEdge g "Palmanova" "Trieste")
(graphAddEdge g "Trieste" "Postojna")
(graphAddEdge g "Postojna" "Ljubljana")
(graphAddEdge g "Ljubljana" "Zagreb")
(graphAddEdge g "Zagreb" "Slavonski Brod")
(graphAddEdge g "Slavonski Brod" "Belgrade")
(graphAddEdge g "Belgrade" "Vrsac")
(graphAddEdge g "Vrsac" "Timisoara")
(graphAddEdge g "Timisoara" "Drobeta")
(graphAddEdge g "Drobeta" "Turnu Severin")
(graphAddEdge g "Turnu Severin" "Craiova")
(graphAddEdge g "Craiova" "Alexandria")
(graphAddEdge g "Alexandria" "Bucharest")
(graphAddEdge g "Bucharest" "Giurgiu")
(graphAddEdge g "Giurgiu" "Ruse")
(graphAddEdge g "Ruse" "Razgrad")
(graphAddEdge g "Razgrad" "Shoumen")
(graphAddEdge g "Shoumen" "Varna")
(graphAddEdge g "Turkmenbashi" "Gyzylarbat")
(graphAddEdge g "Gyzylarbat" "Ashgabat")
(graphAddEdge g "Ashgabat" "Tedjen")
(graphAddEdge g "Tedjen" "Mary")
(graphAddEdge g "Mary" "Chardzhu")
(graphAddEdge g "Chardzhu" "Alat")
(graphAddEdge g "Alat" "Buchara")
(graphAddEdge g "Buchara" "Karshi")
(graphAddEdge g "Karshi" "Guzai")
(graphAddEdge g "Guzai" "Sherobod")
(graphAddEdge g "Sherobod" "Termis")
(graphAddEdge g "Termis" "Dushanbe")
(graphAddEdge g "Dushanbe" "Jirgatal")
(graphAddEdge g "Jirgatal" "Sary Tash")
(graphAddEdge g "Sary Tash" "Irkeshtam")
(graphAddEdge g "Poti" "Samtredia")
(graphAddEdge g "Samtredia" "Khashuri")
(graphAddEdge g "Khashuri" "Tbilisi")
(graphAddEdge g "Tbilisi" "Ganca")
(graphAddEdge g "Ganca" "Evlak")
(graphAddEdge g "Evlak" "Baku")
(graphAddEdge g "Brest" "Lorient")
(graphAddEdge g "Lorient" "Vannes")
(graphAddEdge g "Vannes" "Nantes")
(graphAddEdge g "Nantes" "Angers")
(graphAddEdge g "Angers" "Tours")
(graphAddEdge g "Tours" "Orléans")
(graphAddEdge g "Orléans" "Montargis")
(graphAddEdge g "Montargis" "Auxerre")
(graphAddEdge g "Auxerre" "Beaune")
(graphAddEdge g "Beaune" "Dole")
(graphAddEdge g "Dole" "Besançon")
(graphAddEdge g "Besançon" "Belfort")
(graphAddEdge g "Belfort" "Mulhouse")
(graphAddEdge g "Mulhouse" "Basel")
(graphAddEdge g "Basel" "Zürich")
(graphAddEdge g "Zürich" "Winterthur")
(graphAddEdge g "Winterthur" "St. Gallen")
(graphAddEdge g "St. Gallen" "St. Margrethen")
(graphAddEdge g "St. Margrethen" "Bregenz")
(graphAddEdge g "Bregenz" "Feldkirch")
(graphAddEdge g "Feldkirch" "Landeck")
(graphAddEdge g "Landeck" "Telfs")
(graphAddEdge g "Telfs" "Innsbruck")
(graphAddEdge g "Innsbruck" "Lauterach")
(graphAddEdge g "Lauterach" "Feldkirch")
(graphAddEdge g "Feldkirch" "Imst")
(graphAddEdge g "Imst" "Innsbruck")
(graphAddEdge g "Innsbruck" "Wörgl")
(graphAddEdge g "Wörgl" "Rosenheim")
(graphAddEdge g "Rosenheim" "Bad Reichenhall")
(graphAddEdge g "Bad Reichenhall" "Salzburg")
(graphAddEdge g "Salzburg" "Sattledt")
(graphAddEdge g "Sattledt" "Linz")
(graphAddEdge g "Linz" "Sankt Pölten")
(graphAddEdge g "Sankt Pölten" "Vienna")
(graphAddEdge g "Vienna" "Nickelsdorf")
(graphAddEdge g "Nickelsdorf" "Mosonmagyaróvár")
(graphAddEdge g "Mosonmagyaróvár" "Budapest")
(graphAddEdge g "Budapest" "Szolnok")
(graphAddEdge g "Szolnok" "Püspökladány")
(graphAddEdge g "Püspökladány" "Oradea")
(graphAddEdge g "Oradea" "Cluj")
(graphAddEdge g "Cluj" "Napoca")
(graphAddEdge g "Napoca" "Turda")
(graphAddEdge g "Turda" "Târgu Mures")
(graphAddEdge g "Târgu Mures" "Brasov")
(graphAddEdge g "Brasov" "Ploiesti")
(graphAddEdge g "Ploiesti" "Bucharest")
(graphAddEdge g "Bucharest" "Urziceni")
(graphAddEdge g "Urziceni" "Slobozia")
(graphAddEdge g "Slobozia" "Hîrsova")
(graphAddEdge g "Hîrsova" "Constanta")
(graphAddEdge g "Brest" "Rennes")
(graphAddEdge g "Rennes" "Le Mans")
(graphAddEdge g "Le Mans" "Paris")
(graphAddEdge g "Paris" "Reims")
(graphAddEdge g "Reims" "Metz")
(graphAddEdge g "Metz" "Saarbrücken")
(graphAddEdge g "Saarbrücken" "Mannheim")
(graphAddEdge g "Mannheim" "Heilbronn")
(graphAddEdge g "Heilbronn" "Nuremberg")
(graphAddEdge g "Nuremberg" "Rozvadov")
(graphAddEdge g "Rozvadov" "Plzen")
(graphAddEdge g "Plzen" "Prague")
(graphAddEdge g "Prague" "Jihlava")
(graphAddEdge g "Jihlava" "Brno")
(graphAddEdge g "Brno" "Trencin")
(graphAddEdge g "Trencin" "Prešov")
(graphAddEdge g "Prešov" "Vyšné Nemecké")
(graphAddEdge g "Vyšné Nemecké" "Uzhhorod")
(graphAddEdge g "Uzhhorod" "Mukacheve")
(graphAddEdge g "Mukacheve" "Stryj")
(graphAddEdge g "Stryj" "Ternopil'")
(graphAddEdge g "Ternopil'" "Khmel'nyts'kyi")
(graphAddEdge g "Khmel'nyts'kyi" "Vinnytsia")
(graphAddEdge g "Vinnytsia" "Uman'")
(graphAddEdge g "Uman'" "Kirovohrad")
(graphAddEdge g "Kirovohrad" "Dnipropetrovsk")
(graphAddEdge g "Dnipropetrovsk" "Donetsk")
(graphAddEdge g "Donetsk" "Rostov na Donu")
(graphAddEdge g "Rostov na Donu" "Armavir")
(graphAddEdge g "Armavir" "Mineralnye Vody")
(graphAddEdge g "Mineralnye Vody" "Makhachkala")
(graphAddEdge g "Calais" "Oostende")
(graphAddEdge g "Oostende" "Brugge")
(graphAddEdge g "Brugge" "Ghent")
(graphAddEdge g "Ghent" "Brussels")
(graphAddEdge g "Brussels" "Liège")
(graphAddEdge g "Liège" "Aachen")
(graphAddEdge g "Aachen" "Cologne")
(graphAddEdge g "Cologne" "Olpe")
(graphAddEdge g "Olpe" "Wetzlar")
(graphAddEdge g "Wetzlar" "Bad Hersfeld")
(graphAddEdge g "Bad Hersfeld" "Eisenach")
(graphAddEdge g "Eisenach" "Erfurt")
(graphAddEdge g "Erfurt" "Gera")
(graphAddEdge g "Gera" "Chemnitz")
(graphAddEdge g "Chemnitz" "Dresden")
(graphAddEdge g "Dresden" "Görlitz")
(graphAddEdge g "Görlitz" "Legnica")
(graphAddEdge g "Legnica" "Wroclaw")
(graphAddEdge g "Wroclaw" "Opole")
(graphAddEdge g "Opole" "Gliwice")
(graphAddEdge g "Gliwice" "Kraków")
(graphAddEdge g "Kraków" "Przemysl")
(graphAddEdge g "Przemysl" "L'viv")
(graphAddEdge g "L'viv" "Rivne")
(graphAddEdge g "Rivne" "Zhytomyr")
(graphAddEdge g "Zhytomyr" "Kyiv")
(graphAddEdge g "Kyiv" "Kharkiv")
(graphAddEdge g "Kharkiv" "Luhans'k")
(graphAddEdge g "Luhans'k" "Volgograd")
(graphAddEdge g "Volgograd" "Astrakhan")
(graphAddEdge g "Astrakhan" "Atyrau")
(graphAddEdge g "Atyrau" "Beineu")
(graphAddEdge g "Beineu" "Kungrad")
(graphAddEdge g "Kungrad" "Nukus")
(graphAddEdge g "Nukus" "Dasoguz")
(graphAddEdge g "Dasoguz" "Buchara")
(graphAddEdge g "Buchara" "Navoi")
(graphAddEdge g "Navoi" "Samarkand")
(graphAddEdge g "Samarkand" "Jizzakh")
(graphAddEdge g "Jizzakh" "Tashkent")
(graphAddEdge g "Tashkent" "Shymkent")
(graphAddEdge g "Shymkent" "Zhambyl")
(graphAddEdge g "Zhambyl" "Bishkek")
(graphAddEdge g "Bishkek" "Almaty")
(graphAddEdge g "Almaty" "Sary")
(graphAddEdge g "Sary" "Ozek")
(graphAddEdge g "Ozek" "Taldykorgan")
(graphAddEdge g "Taldykorgan" "Ucharal")
(graphAddEdge g "Ucharal" "Taskesken")
(graphAddEdge g "Taskesken" "Ayaguz")
(graphAddEdge g "Ayaguz" "Georgiyevska")
(graphAddEdge g "Georgiyevska" "Öskemen")
(graphAddEdge g "Öskemen" "Ridder")
(graphAddEdge g "Hoek van Holland" "The Hague")
(graphAddEdge g "The Hague" "Gouda")
(graphAddEdge g "Gouda" "Utrecht")
(graphAddEdge g "Utrecht" "Amersfoort")
(graphAddEdge g "Amersfoort" "Oldenzaal")
(graphAddEdge g "Oldenzaal" "Osnabrück")
(graphAddEdge g "Osnabrück" "Bad Oeynhausen")
(graphAddEdge g "Bad Oeynhausen" "Hanover")
(graphAddEdge g "Hanover" "Braunschweig")
(graphAddEdge g "Braunschweig" "Magdeburg")
(graphAddEdge g "Magdeburg" "Berlin")
(graphAddEdge g "Berlin" "Swiebodzin")
(graphAddEdge g "Swiebodzin" "Poznan")
(graphAddEdge g "Poznan" "Warsaw")
(graphAddEdge g "Warsaw" "Brest")
(graphAddEdge g "Brest" "Minsk")
(graphAddEdge g "Minsk" "Smolensk")
(graphAddEdge g "Smolensk" "Moscow")
(graphAddEdge g "Moscow" "Ryazan")
(graphAddEdge g "Ryazan" "Penza")
(graphAddEdge g "Penza" "Samara")
(graphAddEdge g "Samara" "Ufa")
(graphAddEdge g "Ufa" "Chelyabinsk")
(graphAddEdge g "Chelyabinsk" "Kurgan")
(graphAddEdge g "Kurgan" "Ishim")
(graphAddEdge g "Ishim" "Omsk")
(graphAddEdge g "Fishguard" "Swansea")
(graphAddEdge g "Swansea" "Cardiff")
(graphAddEdge g "Cardiff" "Newport")
(graphAddEdge g "Newport" "Bristol")
(graphAddEdge g "Bristol" "London")
(graphAddEdge g "London" "Colchester")
(graphAddEdge g "Colchester" "Ipswich")
(graphAddEdge g "Ipswich" "Felixstowe")
(graphAddEdge g "Cork" "Waterford")
(graphAddEdge g "Waterford" "Wexford")
(graphAddEdge g "Wexford" "Rosslare")
(graphAddEdge g "Tallinn" "Narva")
(graphAddEdge g "Narva" "Saint Petersburg")
(graphAddEdge g "Esbjerg" "Copenhagen")
(graphAddEdge g "Copenhagen" "Malmö")
(graphAddEdge g "Malmö" "Helsingborg")
(graphAddEdge g "Helsingborg" "Halmstad")
(graphAddEdge g "Halmstad" "Gothenburg")
(graphAddEdge g "Gothenburg" "Örebro")
(graphAddEdge g "Örebro" "Stockholm")
(graphAddEdge g "Liverpool" "Manchester")
(graphAddEdge g "Manchester" "Kingston upon Hull")
(graphAddEdge g "Shannon" "Limerick")
(graphAddEdge g "Limerick" "Dublin")
(graphAddEdge g "Melbu" "Sortland")
(graphAddEdge g "Sortland" "Lødingen")
(graphAddEdge g "Lødingen" "Evenes")
(graphAddEdge g "Evenes" "Narvik")
(graphAddEdge g "Narvik" "Kiruna")
(graphAddEdge g "Kiruna" "Töre")
(graphAddEdge g "Töre" "Luleå")
(graphAddEdge g "Å" "Svolvær")
(graphAddEdge g "Omsk" "Pavlodar")
(graphAddEdge g "Pavlodar" "Semey")
(graphAddEdge g "Semey" "Georgiyevka")
(graphAddEdge g "Georgiyevka" "Maikapshagai")
(graphAddEdge g "Petropavl" "Astana")
(graphAddEdge g "Astana" "Karagandy")
(graphAddEdge g "Karagandy" "Balkhash")
(graphAddEdge g "Balkhash" "Burubaytal")
(graphAddEdge g "Burubaytal" "Almaty")
(graphAddEdge g "Almaty" "Bishkek")
(graphAddEdge g "Bishkek" "Naryn")
(graphAddEdge g "Naryn" "Torugart")
(graphAddEdge g "Chelyabinsk" "Kostanai")
(graphAddEdge g "Kostanai" "Esil")
(graphAddEdge g "Esil" "Derzhavinsk")
(graphAddEdge g "Derzhavinsk" "Arkalyk")
(graphAddEdge g "Arkalyk" "Zhezkazgan")
(graphAddEdge g "Zhezkazgan" "Kyzylorda")
(graphAddEdge g "Kyzylorda" "Shymkent")
(graphAddEdge g "Shymkent" "Tashkent")
(graphAddEdge g "Tashkent" "Ayni")
(graphAddEdge g "Ayni" "Dushanbe")
(graphAddEdge g "Dushanbe" "Nizhniy Panj")
(graphAddEdge g "Samara" "Uralsk")
(graphAddEdge g "Uralsk" "Atyrau")
(graphAddEdge g "Atyrau" "Beineu")
(graphAddEdge g "Beineu" "Shetpe")
(graphAddEdge g "Shetpe" "Zhetybai")
(graphAddEdge g "Zhetybai" "Fetisovo")
(graphAddEdge g "Fetisovo" "Bekdash")
(graphAddEdge g "Bekdash" "Turkmenbashi")
(graphAddEdge g "Turkmenbashi" "Gyzylarbat")
(graphAddEdge g "Gyzylarbat" "Border of the Islamic Republic of Iran")
(graphAddEdge g "Moscow" "Tambov")
(graphAddEdge g "Tambov" "Povorino")
(graphAddEdge g "Povorino" "Volgograd")
(graphAddEdge g "Volgograd" "Astrakhan")
(graphAddEdge g "Astrakhan" "Makhachkala")
(graphAddEdge g "Makhachkala" "Kuba")
(graphAddEdge g "Kuba" "Baku")
(graphAddEdge g "Baku" "Alyat")
(graphAddEdge g "Alyat" "Astara")
(graphAddEdge g "Mineralnye Vody" "Nalchik")
(graphAddEdge g "Nalchik" "Vladikavkaz")
(graphAddEdge g "Vladikavkaz" "Tbilisi")
(graphAddEdge g "Tbilisi" "Yerevan")
(graphAddEdge g "Yerevan" "Goris")
(graphAddEdge g "Goris" "Megri")
(graphAddEdge g "Yaroslavl" "Moscow")
(graphAddEdge g "Moscow" "Voronezh")
(graphAddEdge g "Voronezh" "Novorossijsk")
(graphAddEdge g "Kirkenes" "Murmansk")
(graphAddEdge g "Murmansk" "Petrozavodsk")
(graphAddEdge g "Petrozavodsk" "Saint Petersburg")
(graphAddEdge g "Saint Petersburg" "Moscow")
(graphAddEdge g "Moscow" "Orel")
(graphAddEdge g "Orel" "Kharkiv")
(graphAddEdge g "Kharkiv" "Simferopol")
(graphAddEdge g "Simferopol" "Alushta")
(graphAddEdge g "Alushta" "Yalta")
(graphAddEdge g "Moscow" "Kaluga")
(graphAddEdge g "Kaluga" "Brjansk")
(graphAddEdge g "Brjansk" "Glukhov")
(graphAddEdge g "Glukhov" "Kyiv")
(graphAddEdge g "Samsun" "Merzifon")
(graphAddEdge g "Saint Petersburg" "Pskov")
(graphAddEdge g "Pskov" "Homel")
(graphAddEdge g "Homel" "Kyiv")
(graphAddEdge g "Kyiv" "Odesa")
(graphAddEdge g "Klaipeda" "Kaunas")
(graphAddEdge g "Kaunas" "Vilnius")
(graphAddEdge g "Vilnius" "Lida")
(graphAddEdge g "Lida" "Slonim")
(graphAddEdge g "Slonim" "Kobrin")
(graphAddEdge g "Kobrin" "Dubno")
(graphAddEdge g "Dubno" "Ternopil'")
(graphAddEdge g "Ternopil'" "Chernivtsi")
(graphAddEdge g "Chernivtsi" "Siret")
(graphAddEdge g "Siret" "Suceava")
(graphAddEdge g "Suceava" "Roman")
(graphAddEdge g "Roman" "Urziceni")
(graphAddEdge g "Urziceni" "Bucharest")
(graphAddEdge g "Bucharest" "Giurgiu")
(graphAddEdge g "Giurgiu" "Ruse")
(graphAddEdge g "Ruse" "Byala")
(graphAddEdge g "Byala" "Veliko Tarnovo")
(graphAddEdge g "Veliko Tarnovo" "Stara Zagora")
(graphAddEdge g "Stara Zagora" "Haskovo")
(graphAddEdge g "Haskovo" "Svilengrad")
(graphAddEdge g "Svilengrad" "Ormenio")
(graphAddEdge g "Ormenio" "Kastanies")
(graphAddEdge g "Kastanies" "Didymoteicho")
(graphAddEdge g "Didymoteicho" "Alexandroupolis")
(graphAddEdge g "Chaniá" "Iraklion")
(graphAddEdge g "Iraklion" "Agios Nikolaos")
(graphAddEdge g "Agios Nikolaos" "Sitía")
(graphAddEdge g "Gdansk" "Swiecie")
(graphAddEdge g "Swiecie" "Lódz")
(graphAddEdge g "Lódz" "Piotrków Trybunalski")
(graphAddEdge g "Piotrków Trybunalski" "Katowice")
(graphAddEdge g "Katowice" "Žilina")
(graphAddEdge g "Žilina" "Bratislava")
(graphAddEdge g "Bratislava" "Gyor")
(graphAddEdge g "Gyor" "Budapest")
(graphAddEdge g "Budapest" "Szeged")
(graphAddEdge g "Szeged" "Belgrade")
(graphAddEdge g "Belgrade" "Niš")
(graphAddEdge g "Niš" "Kumanovo")
(graphAddEdge g "Kumanovo" "Skopje")
(graphAddEdge g "Skopje" "Thessaloniki")
(graphAddEdge g "Thessaloniki" "Larissa")
(graphAddEdge g "Larissa" "Lamia")
(graphAddEdge g "Lamia" "Athens")
(graphAddEdge g "Vardø" "Vadsø")
(graphAddEdge g "Vadsø" "Varangerbotn")
(graphAddEdge g "Varangerbotn" "Utsjoki")
(graphAddEdge g "Utsjoki" "Inari")
(graphAddEdge g "Inari" "Ivalo")
(graphAddEdge g "Ivalo" "Sodankylä")
(graphAddEdge g "Sodankylä" "Rovaniemi")
(graphAddEdge g "Rovaniemi" "Kemi")
(graphAddEdge g "Kemi" "Oulu")
(graphAddEdge g "Oulu" "Jyväskylä")
(graphAddEdge g "Jyväskylä" "Heinola")
(graphAddEdge g "Heinola" "Lahti")
(graphAddEdge g "Lahti" "Helsinki")
(graphAddEdge g "Kissamos" "Chaniá")
(graphAddEdge g "Rhion" "Egion")
(graphAddEdge g "Egion" "Korinthos")
(graphAddEdge g "Korinthos" "Tripoli")
(graphAddEdge g "Tripoli" "Kalamata")
(graphAddEdge g "Swinoujscie" "Wolin")
(graphAddEdge g "Wolin" "Goleniów")
(graphAddEdge g "Goleniów" "Szczecin")
(graphAddEdge g "Szczecin" "Gorzów Wielkopolski")
(graphAddEdge g "Gorzów Wielkopolski" "Swiebodzin")
(graphAddEdge g "Swiebodzin" "Zielona Góra")
(graphAddEdge g "Zielona Góra" "Legnica")
(graphAddEdge g "Legnica" "Jelenia Góra")
(graphAddEdge g "Jelenia Góra" "Harrachov")
(graphAddEdge g "Harrachov" "Železný Brod")
(graphAddEdge g "Železný Brod" "Turnov")
(graphAddEdge g "Turnov" "Mladá Boleslav")
(graphAddEdge g "Mladá Boleslav" "Prague")
(graphAddEdge g "Prague" "Jihlava")
(graphAddEdge g "Jihlava" "Brno")
(graphAddEdge g "Brno" "Bratislava")
(graphAddEdge g "Bratislava" "Rajka")
(graphAddEdge g "Rajka" "Csorna")
(graphAddEdge g "Csorna" "Szombathely")
(graphAddEdge g "Szombathely" "Zalaegerszeg")
(graphAddEdge g "Zalaegerszeg" "Nagykanizsa")
(graphAddEdge g "Nagykanizsa" "Letenye")
(graphAddEdge g "Letenye" "Zagreb")
(graphAddEdge g "Zagreb" "Karlovac")
(graphAddEdge g "Karlovac" "Rijeka")
(graphAddEdge g "Rijeka" "Split")
(graphAddEdge g "Split" "Dubrovnik")
(graphAddEdge g "Dubrovnik" "Petrovac")
(graphAddEdge g "Petrovac" "Podgorica")
(graphAddEdge g "Podgorica" "Bijelo Polje")
(graphAddEdge g "Bijelo Polje" "Skopje")
(graphAddEdge g "Skopje" "Kicevo")
(graphAddEdge g "Kicevo" "Ohrid")
(graphAddEdge g "Ohrid" "Bitola")
(graphAddEdge g "Bitola" "Niki")
(graphAddEdge g "Niki" "Vevi")
(graphAddEdge g "Vevi" "Kozani")
(graphAddEdge g "Kozani" "Larissa")
(graphAddEdge g "Larissa" "Domokos")
(graphAddEdge g "Domokos" "Lamia")
(graphAddEdge g "Lamia" "Brallos")
(graphAddEdge g "Brallos" "Itea")
(graphAddEdge g "Itea" "Antirrion")
(graphAddEdge g "Malmö" "Ystad")
(graphAddEdge g "Igoumenitsa" "Preveza")
(graphAddEdge g "Preveza" "Rhion")
(graphAddEdge g "Rhion" "Patrai")
(graphAddEdge g "Patrai" "Pyrgos")
(graphAddEdge g "Pyrgos" "Kalamáta")
(graphAddEdge g "Rostock" "Berlin")
(graphAddEdge g "Berlin" "Lübbenau")
(graphAddEdge g "Lübbenau" "Dresden")
(graphAddEdge g "Dresden" "Teplice")
(graphAddEdge g "Teplice" "Prague")
(graphAddEdge g "Prague" "Tábor")
(graphAddEdge g "Tábor" "Linz")
(graphAddEdge g "Linz" "Salzburg")
(graphAddEdge g "Salzburg" "Villach")
(graphAddEdge g "Villach" "Tarvisio")
(graphAddEdge g "Tarvisio" "Udine")
(graphAddEdge g "Udine" "Palmanova")
(graphAddEdge g "Palmanova" "Mestre")
(graphAddEdge g "Mestre" "Ravenna")
(graphAddEdge g "Ravenna" "Cesena")
(graphAddEdge g "Cesena" "Rimini")
(graphAddEdge g "Rimini" "Fano")
(graphAddEdge g "Fano" "Ancona")
(graphAddEdge g "Ancona" "Pescara")
(graphAddEdge g "Pescara" "Canosa")
(graphAddEdge g "Canosa" "Bari")
(graphAddEdge g "Bari" "Brindisi")
(graphAddEdge g "Helsingør" "Copenhagen")
(graphAddEdge g "Copenhagen" "Køge")
(graphAddEdge g "Køge" "Vordingborg")
(graphAddEdge g "Vordingborg" "Farø")
(graphAddEdge g "Farø" "Nykøbing Falster")
(graphAddEdge g "Nykøbing Falster" "Gedser")
(graphAddEdge g "Messina" "Catania")
(graphAddEdge g "Catania" "Siracusa")
(graphAddEdge g "Siracusa" "Gela")
(graphAddEdge g "Fredrikshavn" "Aalborg")
(graphAddEdge g "Aalborg" "Århus")
(graphAddEdge g "Århus" "Vejle")
(graphAddEdge g "Vejle" "Kolding")
(graphAddEdge g "Kolding" "Frøslev")
(graphAddEdge g "Frøslev" "Flensburg")
(graphAddEdge g "Flensburg" "Hamburg")
(graphAddEdge g "Hamburg" "Hanover")
(graphAddEdge g "Hanover" "Göttingen")
(graphAddEdge g "Göttingen" "Kassel")
(graphAddEdge g "Kassel" "Fulda")
(graphAddEdge g "Fulda" "Würzburg")
(graphAddEdge g "Würzburg" "Nuremberg")
(graphAddEdge g "Nuremberg" "Munich")
(graphAddEdge g "Munich" "Rosenheim")
(graphAddEdge g "Rosenheim" "Wörgl")
(graphAddEdge g "Wörgl" "Innsbruck")
(graphAddEdge g "Innsbruck" "Brenner")
(graphAddEdge g "Brenner" "Fortezza")
(graphAddEdge g "Fortezza" "Bozen")
(graphAddEdge g "Bozen" "Trento")
(graphAddEdge g "Trento" "Verona")
(graphAddEdge g "Verona" "Modena")
(graphAddEdge g "Modena" "Bologna")
(graphAddEdge g "Bologna" "Cesena")
(graphAddEdge g "Cesena" "Perugia")
(graphAddEdge g "Perugia" "Fiano")
(graphAddEdge g "Fiano" "Naples")
(graphAddEdge g "Naples" "Salerno")
(graphAddEdge g "Salerno" "Sicignano")
(graphAddEdge g "Sicignano" "Cosenza")
(graphAddEdge g "Cosenza" "Villa San Giovanni")
(graphAddEdge g "Amsterdam" "Utrecht")
(graphAddEdge g "Utrecht" "Arnhem")
(graphAddEdge g "Arnhem" "Emmerich")
(graphAddEdge g "Emmerich" "Oberhausen")
(graphAddEdge g "Oberhausen" "Cologne")
(graphAddEdge g "Cologne" "Frankfurt am Main")
(graphAddEdge g "Frankfurt am Main" "Heidelberg")
(graphAddEdge g "Heidelberg" "Karlsruhe")
(graphAddEdge g "Karlsruhe" "Offenburg")
(graphAddEdge g "Offenburg" "Basel")
(graphAddEdge g "Basel" "Olten")
(graphAddEdge g "Olten" "Lucerne")
(graphAddEdge g "Lucerne" "Altdorf")
(graphAddEdge g "Altdorf" "San Gottardo")
(graphAddEdge g "San Gottardo" "Bellinzona")
(graphAddEdge g "Bellinzona" "Lugano")
(graphAddEdge g "Lugano" "Chiasso")
(graphAddEdge g "Chiasso" "Como")
(graphAddEdge g "Como" "Milan")
(graphAddEdge g "Milan" "Piacenza")
(graphAddEdge g "Piacenza" "Parma")
(graphAddEdge g "Parma" "Modena")
(graphAddEdge g "Modena" "Florence")
(graphAddEdge g "Florence" "Rome")
(graphAddEdge g "Porto Torres" "Sassari")
(graphAddEdge g "Sassari" "Cagliari")
(graphAddEdge g "Bastia" "Porto Vecchio")
(graphAddEdge g "Porto Vecchio" "Bonifacio")
(graphAddEdge g "Hoek van Holland" "Rotterdam")
(graphAddEdge g "Rotterdam" "Eindhoven")
(graphAddEdge g "Eindhoven" "Maastricht")
(graphAddEdge g "Maastricht" "Liège")
(graphAddEdge g "Liège" "Bastogne")
(graphAddEdge g "Bastogne" "Arlon")
(graphAddEdge g "Arlon" "Luxembourg")
(graphAddEdge g "Luxembourg" "Metz")
(graphAddEdge g "Metz" "Saint")
(graphAddEdge g "Saint" "Avold")
(graphAddEdge g "Avold" "Strasbourg")
(graphAddEdge g "Strasbourg" "Mulhouse")
(graphAddEdge g "Mulhouse" "Basel")
(graphAddEdge g "Basel" "Olten")
(graphAddEdge g "Olten" "Berne")
(graphAddEdge g "Berne" "Lausanne")
(graphAddEdge g "Lausanne" "Geneva")
(graphAddEdge g "Geneva" "Mont Blanc")
(graphAddEdge g "Mont Blanc" "Aosta")
(graphAddEdge g "Aosta" "Ivrea")
(graphAddEdge g "Ivrea" "Vercelli")
(graphAddEdge g "Vercelli" "Alessandria")
(graphAddEdge g "Alessandria" "Genova")
(graphAddEdge g "Calais" "Paris")
(graphAddEdge g "Paris" "Lyon")
(graphAddEdge g "Lyon" "Orange")
(graphAddEdge g "Orange" "Narbonne")
(graphAddEdge g "Narbonne" "Girona")
(graphAddEdge g "Girona" "Barcelona")
(graphAddEdge g "Barcelona" "Tarragona")
(graphAddEdge g "Tarragona" "Castellón de la Plana")
(graphAddEdge g "Castellón de la Plana" "Valencia")
(graphAddEdge g "Valencia" "Alicante")
(graphAddEdge g "Alicante" "Murcia")
(graphAddEdge g "Murcia" "Almería")
(graphAddEdge g "Almería" "Málaga")
(graphAddEdge g "Málaga" "Algeciras")
(graphAddEdge g "Inverness" "Perth")
(graphAddEdge g "Perth" "Edinburgh")
(graphAddEdge g "Edinburgh" "Newcastle")
(graphAddEdge g "Newcastle" "London")
(graphAddEdge g "London" "Folkestone")
(graphAddEdge g "Folkestone" "Dover")
(graphAddEdge g "Le Havre" "Paris")
(graphAddEdge g "Paris" "Orléans")
(graphAddEdge g "Orléans" "Bordeaux")
(graphAddEdge g "Bordeaux" "San Sebastian")
(graphAddEdge g "San Sebastian" "Madrid")
(graphAddEdge g "Madrid" "Sevilla")
(graphAddEdge g "Sevilla" "Algeciras")
(graphAddEdge g "Greenock" "Glasgow")
(graphAddEdge g "Glasgow" "Preston")
(graphAddEdge g "Preston" "Birmingham")
(graphAddEdge g "Birmingham" "Southampton")
nil
